### ISSUE TITLE
Grammar is in an endless loop

### ISSUE THREAD

**Issue by Damanox** [Pure-D/code-d#102]
Received this error after opening folder with the project
![error](https://cloud.githubusercontent.com/assets/545324/21742792/76f9eb6a-d4fe-11e6-8490-81c954d18f9d.png)

OS: Windows 10 x64
Code-D: 0.15.1
Workspace-D: 2.9.1
Project: https://github.com/Damanox/supaplex-d

**Comment by WebFreak001** [comment]
Should be fixed when we changed grammars
