### ISSUE TITLE
Manual installation 'master' branch does not work with vscode 1.8.1 windows & linux

### ISSUE THREAD

**Issue by ArjanKn** [Pure-D/code-d#104]
The last command 
`node ./node_modules/vscode/bin/compile`
returns:
```
The vscode extension module got updated to TypeScript 2.0.x.
Please see https://code.visualstudio.com/updates/v1_6#_extension-authoring for instruction on how to migrate your extension.
```
Versions:
vscode 1.8,1
shell 1.4.6
node 6.5.0

**Comment by WebFreak001** [comment]
delete `node_modules` and do `npm install`. That command isn't needed anymore. Just run the extension in vscode. Open the extension folder in vscode, go to debug and press start

**Comment by WebFreak001** [comment]
https://github.com/Pure-D/code-d/commit/54caa18f98c42368bfe78628280b95041e4874ac
