### ISSUE TITLE
DCD autocompletion broken on Windows

### ISSUE THREAD

**Issue by aka-demik** [Pure-D/code-d#105]
It work fine from dcd-client:
```batch
> dcd-client.exe -l -c 3074 d:\Work\multiport\src\dll-web-interface\source\web\standard.d
d:\Work\Multiport\src\dll-web-interface\source\multiport\types\global.d 3279
```

But "Go to definition" (F12) and "Go to the symbol in the file" (Ctrl+Shift+O) does not work.
[vscode.log.zip](https://github.com/Pure-D/code-d/files/716002/vscode.zip)

**Comment by WebFreak001** [comment]
workspace-d hung up, did you compile it with LDC or DMD?

**Comment by aka-demik** [comment]
code-d automatically build workspace-d after update.

Both dmd and ldc2 is available. Somehow I can check which compiler was used?

```shell
> dmd --version
DMD32 D Compiler v2.072.2

> ldc2 --version v
LDC - the LLVM D compiler (1.1.0-beta6):
  based on DMD v2.071.2 and LLVM 3.9.0
  built with LDC - the LLVM D compiler (1.1.0-beta6)
  Default target: x86_64-pc-windows-msvc
  Host CPU: sandybridge
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    arm      - ARM
    armeb    - ARM (big endian)
    mips     - Mips
    mips64   - Mips64 [experimental]
    mips64el - Mips64el [experimental]
    mipsel   - Mipsel
    ppc32    - PowerPC 32
    ppc64    - PowerPC 64
    ppc64le  - PowerPC 64 LE
    sparc    - Sparc
    sparcel  - Sparc LE
    sparcv9  - Sparc V9
    thumb    - Thumb
    thumbeb  - Thumb (big endian)
    x86      - 32-bit X86: Pentium-Pro and above
    x86-64   - 64-bit X86: EM64T and AMD64
```

**Comment by aka-demik** [comment]
I rebuilt workspace-d using https://github.com/Pure-D/workspace-d/blob/master/install.bat

According to log, it used ldc2. And it works.

**Comment by WebFreak001** [comment]
So does auto completion still hang now?

**Comment by aka-demik** [comment]
Oh yeah, I forgot about #38

No. Now everything is working fine.

**Comment by aka-demik** [comment]
Maybe, dmd should not be used for automatic build workspace-d?

**Comment by WebFreak001** [comment]
uh it should do that already, I'm gonna check on code-d later. Though it should have downloaded the prebuilt release for windows which is compiled using LDC. I think I will add a "Compiled with" to the version thing

**Comment by WebFreak001** [comment]
Added compiler info in workspace-d master
