### ISSUE TITLE
Documentation tooltip show ASCII only

### ISSUE THREAD

**Issue by aka-demik** [Pure-D/code-d#106]
Screenshot with Cyrillic in documentation:
![default](https://cloud.githubusercontent.com/assets/5939623/22099931/65da9bc4-de3e-11e6-8fcb-a3f3561585b2.png)

**Comment by WebFreak001** [comment]
DCD issue: https://github.com/Hackerpilot/DCD/issues/360

**Comment by WebFreak001** [comment]
Fixed in dcd 0.9.0
