### ISSUE TITLE
add a way to restart and reload dcd

### ISSUE THREAD

**Issue by yannick** [Pure-D/code-d#11]
- each open window should have its own dcd server on a specific port
- there should be a command to reload all files and update them (e.g. if a new dependency is added to dub.json/dub.sdl)
- there should be a command to completely restart the server e.g. if it has crashed

**Comment by WebFreak001** [comment]
* Already implemented
* Reloading dub files currently works through `Switch Configuration` but better way will be added
* Killing the dcd-server and workspace-d process works but I will probably add an easier way for dub too, as the command is already implemented in the D backend (workspace-d)

**Comment by WebFreak001** [comment]
Fixed in commit d43662c

**Comment by WebFreak001** [comment]
Nvm still need reload

**Comment by WebFreak001** [comment]
Requires workspace-d update
