### ISSUE TITLE
having dub project(s) in subfolder(s)

### ISSUE THREAD

**Issue by Extrawurst** [Pure-D/code-d#111]
maybe related to #110 

i have project, which i want to completely want to see in vscode so i "open folder" the root of it. the d (dub) project is in a subfolder of it though. how can i still make code-d realize to recognize it?

**Comment by WebFreak001** [comment]
Doing that isn't possible right now, the dub.json file needs to be the root of the project. Submodules (child projects referenced from the dub file) aren't implemented yet either https://github.com/Pure-D/code-d/issues/56

**Comment by WebFreak001** [comment]
works now
