### ISSUE TITLE
Intellisense not popping up in some cases

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/code-d#112]
I might have caught a reproducable case where the intellisense does not work -- https://github.com/beast-lang/compiler/blob/e7b1989645375ba0f2d3c799136ec78651268ec4/src/beast/lex/token.d#L68 (you can just clone the repo, it has vs code project settings and everything). `lexer.sourceFile` and `lexer.tokenStartPos` (the `sourceFile` and `tokenStartPos` are not ctrl+clickable). Sometimes, it started working after opening beast.lex.toolkit, but I wasn't able to reproduce that deliberately.

**Comment by WebFreak001** [comment]
It has problems resolving what lexer() returns because context is somewhere too deep inside the import declarations. This is a DCD issue though, so reporting there might help you more
