### ISSUE TITLE
Code-D crashes everytime I open Code

### ISSUE THREAD

**Issue by charles-smith** [Pure-D/code-d#116]
Editor error:

    Workspace-D crashed. Please kill dcd-server if neccessary!

Console messages:

    keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2591  for  extension.align
    extensionHost.ts:282[Extension Host] Initialized code-d
    extensionHost.ts:282[Extension Host] workspace-d version: 2.10.0
    extensionHost.ts:282[Extension Host] dscanner version: v0.4.0
    extensionHost.ts:282[Extension Host] dfmt version: 0.5.0
    extensionHost.ts:282[Extension Host] DCD version: v0.9.0-alpha6
    extensionHost.ts:282[Extension Host] dub version: DUB version 1.2.1, built on Feb 16 2017
    extensionHost.ts:282[Extension Host] dub is ready
    extensionHost.ts:282[Extension Host] DScanner is ready
    extensionHost.ts:282[Extension Host] Dfmt is ready
    extensionHost.ts:282[Extension Host] DlangUI is ready
    extensionHost.ts:282[Extension Host] Importer is ready
    extensionHost.ts:282[Extension Host] WorkspaceD ended with code 3221225477

Any ideas?

Thanks!

**Comment by CaddyDz** [comment]
[workspace-d](https://github.com/Pure-D/workspace-d) is a different package that **code-d** depends on.  
It's most likely that this issue is due to **workspace-d** initialization failure.  
Can you reproduce the issue with a fresh installation of **workspace-d**?

**Comment by WebFreak001** [comment]
Out of memory maybe? How big is the project and how much memory do you have?

**Comment by charles-smith** [comment]
@CaddyDz: I can't seem to get workspace-d to install. I think it's an issue with how I have ldc installed, but I'm not sure the right way to do that. 

@WebFreak001: Opening a folder with a "hello world" seems to work. DCD, Vibe.d, and workspace-d all have the crash when I open them. 16 GB memory, i7 4770k processor. CPU goes up to 33% when VS Code is opening, but memory never gets above 20%.

**Comment by WebFreak001** [comment]
So are you using the prebuilt workspace-d binary? Possibly an issue with some 32 bit application instead of 64 bit. Those can only allocate up to 2gb of memory

**Comment by charles-smith** [comment]
Yes I am. Seems completely reasonable it's a 32bit / 64 bit issue.

**Comment by WebFreak001** [comment]
try compiling DCD and workspace-d or now serve-d with --arch=x86_mscoff (installers should do this already since a few months)
