### ISSUE TITLE
Autocomplete does not works

### ISSUE THREAD

**Issue by nolka** [Pure-D/code-d#119]
Use vs code 1.10.2, and code-d latest version. 

When i try to invoke autocomplete window, dcd-server does not start, and autocomplete does not works properly.

Running on fedora core 24

**Comment by CaddyDz** [comment]
Are you running the latest version of vscode?

**Comment by nolka** [comment]
vscode 1.10.2 is latest version)

**Comment by WebFreak001** [comment]
Can I get the exact code-d version? 0.16.1 yes?

**Comment by nolka** [comment]
Yes, 0.16.1.

**Comment by WebFreak001** [comment]
Open the developer tools (ctrl-shift-P -> developer tools) and go to the console tab at the top, send what it says in there

**Comment by nolka** [comment]
```
4main.js:2360 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/poppingscanNext @ main.js:2360
extensionHost.ts:282[Extension Host] Initialized code-d
extensionHost.ts:282[Extension Host] workspace-d version: 2.10.0
extensionHost.ts:282[Extension Host] WorkspaceD Debug: Config files stored in ["/home/nolka/.config/workspace-d", "/etc/xdg/workspace-d", "/usr/share/kde-settings/kde-profile/default/xdg/workspace-d"]

extensionHost.ts:282[Extension Host] dscanner version: v0.4.0 3c3fbe67255e864edab2dd9cfb62bfe0054ffbac

extensionHost.ts:282[Extension Host] dfmt version: 0.5.0

extensionHost.ts:282[Extension Host] DCD version: v0.9.0-alpha6 7cee649587e826c10672c7e13415b2d0391bbcf6

extensionHost.ts:282[Extension Host] dub version: DUB version 1.2.1, built on Feb 16 2017

extensionHost.ts:282[Extension Host] dub is ready
extensionHost.ts:282[Extension Host] DScanner is ready
extensionHost.ts:282[Extension Host] Dfmt is ready
extensionHost.ts:282[Extension Host] DlangUI is ready
extensionHost.ts:282[Extension Host] Importer is ready
extensionHost.ts:282[Extension Host] Configuration: true
extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: object.Exception@/usr/include/dmd/phobos/std/getopt.d(855): Missing value for argument -I.


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ----------------


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x8df4b8]

Server: ??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xa3df3d]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? bool std.getopt.handleOption!(immutable(char)[][]*).handleOption(immutable(char)[], immutable(char)[][]*, ref immutable(char)[][], ref std.getopt.configuration, bool) [0x9766c4]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? void std.getopt.getoptImpl!(immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, void[][immutable(char)[]], void[][immutable(char)[]], immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*) [0x9761a0]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? void std.getopt.getoptImpl!(immutable(char)[], ushort*, immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, void[][immutable(char)[]], void[][immutable(char)[]], immutable(char)[], ushort*, immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*) [0x975790]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? std.getopt.GetoptResult std.getopt.getopt!(immutable(char)[], ushort*, immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*).getopt(ref immutable(char)[][], immutable(char)[], ushort*, immutable(char)[], immutable(char)[][]*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], bool*, immutable(char)[], std.experimental.logger.core.LogLevel*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*) [0x97515b]

Server: ??:? _Dmain [0x966a72]

Server: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xa2cd3f]

Server: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xa2cc67]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xa2cce4]

Server: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xa2cc67]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: ??:? _d_run_main [0xa2cbd3]

Server: ??:? main [0x97f427]

Server: ??:? __libc_start_main [0x99098730]


extensionHost.ts:282[Extension Host] WorkspaceD Debug: Server: 

extensionHost.ts:282[Extension Host] WorkspaceD Debug: DCD-Server stopped with code 1

extensionHost.ts:282[Extension Host] DCD is ready
extensionHost.ts:282[Extension Host] Array[4]
extensionHost.ts:282[Extension Host] Loaded completions for 4 import paths
extensionHost.ts:282[Extension Host] provideHover
extensionHost.ts:282[Extension Host] resolve null
extensionHost.ts:282[Extension Host] provideHover
extensionHost.ts:282[Extension Host] resolve null
extensionHost.ts:282[Extension Host] provideDefinition
extensionHost.ts:282[Extension Host] Resolve null
extensionHost.ts:282[Extension Host] provideDefinition
extensionHost.ts:282[Extension Host] Resolve null
extensionHost.ts:282[Extension Host] provideHover
extensionHost.ts:282[Extension Host] resolve null
extensionHost.ts:282[Extension Host] provideHover
extensionHost.ts:282[Extension Host] resolve null
extensionHost.ts:282[Extension Host] provideHover
extensionHost.ts:282[Extension Host] resolve null
```

**Comment by WebFreak001** [comment]
Hm seems like there is an empty import path... I actually check against empty import paths so I'm not sure how this could happen, is it possible for you to compile workspace-d in debug mode to get more debug information?

Make sure `~/.vscode/extensions/webfreak.code-d-0.16.1/bin/workspace-d` exists first, otherwise change the path in the command below to the path where the old workspace-d binary is

You need to run these commands:
```
cd /tmp
git clone https://github.com/Pure-D/workspace-d
cd workspace-d
dub build
mv workspace-d ~/.vscode/extensions/webfreak.code-d-0.16.1/bin/workspace-d
```

**Comment by nolka** [comment]
I have workspace-d installed:
```
$ ls -lh ~/.vscode/extensions/webfreak.code-d-0.16.1/bin/| grep workspace
-rwxr-xr-x. 1 nolka nolka 15M янв 21 08:53 workspace-d
```

**Comment by nolka** [comment]
i install workspace-d, dfmt, dcd and dscanner at the suggesion by vscode after code-d was installed, and vscode restarted

**Comment by WebFreak001** [comment]
Use the path of workspace-d specified in your vscode user settings

**Comment by nemanja-boric-sociomantic** [comment]
I had the same issue with the `workspace-d` that VS Code auto installed for me after installing `code-d`. Manually building it as described in https://github.com/Pure-D/code-d/issues/119#issuecomment-285685091 made this problem go away.

**Comment by MakersF** [comment]
Same problem here. Trying to recompile to see if it fixes the problem. Something should be done on the code-d extension installed by VS code though, as it was spinning my CPU to 100% and make the laptop last only 1h without power plug

**Comment by MakersF** [comment]
Leaving a follow up here.

Tried to compile, but it failed because of curl. I know the standard library depends on curl, but a novice does not, so the instruction are not clear if you don't have curl installed. Moreover it's not as simple as apt-get install libcurl-dev as that's a metapackage which fails to install (at least on Xubuntu it forces you to pick which package you want).

Once built I check in the vscode directory. There is no bin directory. I guess I installed workspace-d somehow before. I definitely did not build it, so it's probably from the prebuild .deb package.
Indeed I found it in the trash bin, so that's what I used.
Let's inspect it to see what files it put around.
Luckily only /usr/local/bin/workspace-d.
I replaced that file (13 MB) with the newly built one (40 MB).

Now I started VS code and didn't get the errors.

If the prebuild package is not correct it should be updated.

**Comment by WebFreak001** [comment]
Well my file is so small because I compile in release mode and strip away the unused symbols. It possibly doesn't work because of differing libc versions or something like that. If you still have the old binary, can you restore it somewhere and run it in the command line to see if it crashes or if it just waits for input like its supposed to? Not sure if that version had `--version` already built in but you can try.

**Comment by MakersF** [comment]
https://gist.github.com/MakersF/a62db1c3b1c8fcfadac553d36d9cf130

The input was the one showed on the console followed by two new lines and EOF

**Comment by WebFreak001** [comment]
Uh you can't directly enter the commands from there because you need to write 4 binary bytes first so thats why that doesn't work

**Comment by gedaiu** [comment]
![image](https://user-images.githubusercontent.com/4217037/27424186-d8f55cf8-573c-11e7-90d1-1bc1d458eaac.png)

**Comment by dhasenan** [comment]
I'm getting the same problem. When I compiled a debug build from workspace-d HEAD (25319ea2ad58282d67a6dde8b5f374d06e19369c) or tag v2.11.0, the error message in the console went away, but I still didn't get completion. I tried wrapping this in a script that would log when it was started and what it emitted on stdout, but nothing was logged; the script was never invoked.

**Comment by SrMordred** [comment]
Same here server keeps reloading.

WorkspaceD Debug: object.Exception@/usr/include/dmd/phobos/std/getopt.d(880): Missing value for argument -I.

**Comment by carun** [comment]
I encountered the same issue and [this comment](https://github.com/Pure-D/code-d/issues/119#issuecomment-285685091) helped to solve it.

**Comment by WebFreak001** [comment]
should be fixed since DCD and serve-d are now updated

**Comment by LanceAdd** [comment]
hi,i install the plugin(D Programming Language (code-d)) in vscode but after it  finish download something,it can't autocomplete.if something i need to install
