### ISSUE TITLE
Add `module` statement.

### ISSUE THREAD

**Issue by pheerai** [Pure-D/code-d#121]
First of all, amazing work.I tried quite a lot D related editors/plugins/whatsoever, but none beats this one at the moment.

However, there is one minor feature that makes working with larger projects annoying for me: In new files, I have to add the `module`-statement manually, and adding them manually can be a tedious work with several packages in a source tree.

I propose a command `Add default module statement` that adds the module keyword, together with the path (starting from the source root) and filename, to the beginning of the file if none is present, but I'm open for other approaches as well.

I already fiddled around with snippets a bit, but the lack of of regular expressions and knowledge about the workings of VSCode made that a failure.

**Comment by CZDanol** [comment]
https://github.com/Pure-D/workspace-d/issues/78

**Comment by WebFreak001** [comment]
done automatically when creating a file and renaming the file you are currently in (it will insert it as unsaved change that you can undo)
