### ISSUE TITLE
Installer calls fetch/build when settings provide executable dependencies.

### ISSUE THREAD

**Issue by Cody-Duncan** [Pure-D/code-d#122]
After defining these settings:
d.tools.dcd.client
d.tools.dcd.server
d.tools.dfmt
d.tools.dscanner
d.tools.dfix
d.tools.dProfileViewer

D language output indicates the installer attempts to build dependencies:
"
Dub fetch : dfix
Dub build : dfix
Dub fetch : d-profile-viewer
Dub build : d-profile-viewer
Found dcd (client) : dcd-client
Found dcd (server) : dcd-server
DCD : starting server...
Found dfmt : dfmt
Found dscanner : dscanner
"

If these settings are defined, these installation steps should (probably?) be skipped.

**Comment by WebFreak001** [comment]
wrong extension, I think you are looking for https://github.com/dlang-vscode/dlang-vscode

**Comment by Cody-Duncan** [comment]
Woops. You are correct. 

Sincerest apologies, and thank you for the response.
