### ISSUE TITLE
WARN: Could not initialize dub. Falling back to limited functionality!

### ISSUE THREAD

**Issue by AntonOks** [Pure-D/code-d#123]
Getting this since the latest updates, don't know why and don't know of any log to check further...
DUB itself itself , i.e. also via the "TERMNAL" plugin, works fine...

Some additional infos:
OS: Win10
DMD32 D Compiler v2.073.2
VSC: 1.10.2
```
  standard setting for:
    // Path of the dub executable. Path can be omitted if in $PATH or installed using code-d
  "d.dubPath": "dub",
```
DUB (in my $PATH): 1.2.2

---

After closing VSC I'm always getting:
```
std.socket.SocketOSException@std\socket.d(2777): Unable to connect socket...
```

---

Once I set
  "d.neverUseDub": true,
the error doesn't show up :|

**Comment by WebFreak001** [comment]
did you run `dub` to compile once before opening it in code-d? It's most likely due to some dependencies missing or being weird or it also happens if the project output type is `none`

**Comment by notna123** [comment]
yes, I also use DUB over VSC's TERMINAL and (for other projects) natively on the CLI...

**Comment by WebFreak001** [comment]
Can you maybe post your dub.json file (or at least the dependencies) and the error inside the developer tools? (Ctrl-Shift-P -> Toggle Developer Tools -> Click the "Console" tab at the top)

**Comment by WebFreak001** [comment]
The unable to connect to socket bug is now fixed on workspace-d ~master

**Comment by devlo** [comment]
I also have "WARN: Could not initialize dub. Falling back to limited functionality!" on Ubuntu 16.04

This is info from developer tools:


[Extension Host] Initialized code-d
extensionHost.ts:284 [Extension Host] dscanner version: v0.4.0 3c3fbe67255e864edab2dd9cfb62bfe0054ffbac

extensionHost.ts:284 [Extension Host] dfmt version: 0.5.0

extensionHost.ts:284 [Extension Host] DCD version: v0.9.0-alpha6 a734182aabdace66f9f347ff524afc95a01d8857

extensionHost.ts:284 [Extension Host] dub version: DUB version 1.2.2, built on Apr  3 2017

extensionHost.ts:284 [Extension Host] WorkspaceD Debug: Config files stored in 
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: [
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: "/home/user/.config/workspace-d", "/etc/xdg/xdg-ubuntu/workspace-d", 
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: "/usr/share/upstart/xdg/workspace-d", "/etc/xdg/workspace-d"]

extensionHost.ts:284 [Extension Host] workspace-d version: 2.10.0
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: object.Exception@../../.dub/packages/dub-1.2.0-rc.1/dub/source/dub/dependency.d(654): Invalid SemVer format: ^6.1.2
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x942621]
??:? ref dub.dependency.Version dub.dependency.Version.__ctor(immutable(char)[]) [0x946c90]
??:? @property void dub.dependency.Dependency.versionSpec(immutable(char)[]) [0x943bdc]
??:? dub.dependency.Dependency dub.dependency.Dependency.fromJson(dub.internal.vibecompat.data.json.Json) [0x9453db]
??:? dub.dependency.Dependency dub.internal.vibecompat.data.json.deserializeJson!(dub.dependency.Dependency).deserializeJson(dub.internal.vibecompat.data.json.Json) [0xa41b31]
??:? _D3dub6recipe4json9parseJsonFKS3dub6recipe13packagerecipe21BuildSettingsTemplateS3dub8internal10vibecompat4data4json4JsonAyaZ14__foreachbody4MFKAyaKS3dub8internal10vibecompat4data4json4JsonZ14__foreachbody3MFKAyaKS3dub8internal10vibecompat4data4json4JsonZi [0x9e1b21]
??:? _D3dub8internal10vibecompat4data4json4Json7opApplyMFDFKAyaKS3dub8internal10vibecompat4data4json4JsonZiZ14__foreachbody2MFKAyaKS3dub8internal10vibecompat4data4json4JsonZi [0x987e78]
??:? _aaApply2 [0xaf29bc]
??:? int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)) [0x987e07]
??:? int dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.BuildSettingsTemplate, dub.internal.vibecompat.data.json.Json, immutable(char)[]).__foreachbody4(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json) [0x9e0f3e]
??:? _D3dub8internal10vibecompat4data4json4Json7opApplyMFDFKAyaKS3dub8internal10vibecompat4data4json4JsonZiZ14__foreachbody2MFKAyaKS3dub8internal10vibecompat4data4json4JsonZi [0x987e78]
??:? _aaApply2 [0xaf29bc]
??:? int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)) [0x987e07]
??:? void dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.BuildSettingsTemplate, dub.internal.vibecompat.data.json.Json, immutable(char)[]) [0x9e0dee]
??:? void dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.PackageRecipe, dub.internal.vibecompat.data.json.Json, immutable(char)[]) [0x9dfc42]
??:? dub.recipe.packagerecipe.PackageRecipe dub.recipe.io.readPackageRecipe(dub.internal.vibecompat.inet.path.Path, immutable(char)[]) [0x9df425]
??:? dub.package_.Package dub.package_.Package.load(dub.internal.vibecompat.inet.path.Path, dub.internal.vibecompat.inet.path.Path, dub.package_.Package, immutable(char)[]) [0x9abcfc]
??:? dub.package_.Package dub.packagemanager.PackageManager.getOrLoadPackage(dub.internal.vibecompat.inet.path.Path, dub.internal.vibecompat.inet.path.Path, bool) [0x9b1394]
??:? void app.__T16handleRequestModS2010workspaced3com3dubZ.handleRequestMod(int, std.json.JSONValue, ref std.json.JSONValue[], ref int, ref bool, ref bool, const(void delegate(object.Throwable, std.json.JSONValue))) [0x8a2cd8]
??:? void app.handleRequest(int, std.json.JSONValue) [0x891e76]
??:? _Dmain [0x89394d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xaf378e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xaf36d8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xaf374a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xaf36d8]
??:? _d_run_main [0xaf3649]
??:? main [0x8d424f]
??:? __libc_start_main [0xe0cf082f]
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: 

extensionHost.ts:284 [Extension Host] Objectd.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] fsworkspace is ready
extensionHost.ts:284 [Extension Host] DScanner is ready
extensionHost.ts:284 [Extension Host] Dfmt is ready
extensionHost.ts:284 [Extension Host] DlangUI is ready
extensionHost.ts:284 [Extension Host] Importer is ready
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: Server: 2017-04-16T23:54:55.187:server.d:main:133 Starting up...


extensionHost.ts:284 [Extension Host] WorkspaceD Debug: Server: 2017-04-16T23:54:55.187:server.d:main:167 Listening at /tmp/workspace-d-sock6DF


extensionHost.ts:284 [Extension Host] WorkspaceD Debug: Server: 
extensionHost.ts:284 [Extension Host] WorkspaceD Debug: 2017-04-16T23:54:55.193:first.d:visit:325 Could not locate object.d or object.di


extensionHost.ts:284 [Extension Host] WorkspaceD Debug: Server: 2017-04-16T23:54:55.214:first.d:visit:325 Could not locate object.d or object.di

**Comment by WebFreak001** [comment]
@devlo `Invalid SemVer format: ^6.1.2` your dub.json contains this kind of version. I know it's actually correct but dub doesn't support that kind of version. Does `dub upgrade` even work for you? Try using `~>6.1.2` instead (and everywhere else where there is a `^`) and then reload

**Comment by AndrewSChapman** [comment]
Bump - exactly the same issue here.  Dub via the terminal is working fine, however via visual studio code it's  reporting "Could not initialise Dub Falling back to limited functionality".

**Comment by WebFreak001** [comment]
does `dub upgrade` work for you or does it fail?

**Comment by AndrewSChapman** [comment]
If i switch to the VS Code debug terminal, and type "dub upgrade", it works fine.

**Comment by WebFreak001** [comment]
Could you also open the developer tools and send the log in here?

**Comment by AndrewSChapman** [comment]
Here you go :-)

[Extension Host] Initialized code-d
extensionHost.ts:293 [Extension Host] workspace-d version: 2.10.0
extensionHost.ts:293 [Extension Host] dscanner version: v0.4.0

extensionHost.ts:293 [Extension Host] dfmt version: 0.5.0

extensionHost.ts:293 [Extension Host] DCD version: v0.9.0

extensionHost.ts:293 [Extension Host] dub version: DUB version 1.3.0, built on May 31 2017

extensionHost.ts:293 [Extension Host] Objecterror: trueexception: "object.Exception@C:\Users\janju\AppData\Roaming\dub\packages\dub-1.2.0-rc.1\dub\source\dub\dub.d(655): No package pegged was found matching the dependency ~master"msg: "No package pegged was found matching the dependency ~master"request: Object__proto__: Object
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] fsworkspace is ready
extensionHost.ts:293 [Extension Host] DScanner is ready
extensionHost.ts:293 [Extension Host] Dfmt is ready
extensionHost.ts:293 [Extension Host] DlangUI is ready
extensionHost.ts:293 [Extension Host] Importer is ready
extensionHost.ts:293 [Extension Host] WorkspaceD Debug: Config files stored in ["C:\\Users\\Andy Chapman\\AppData\\Local\\workspace-d", "C:\\ProgramData\\workspace-d"]
object.Exception@C:\Users\janju\AppData\Roaming\dub\packages\dub-1.2.0-rc.1\dub\source\dub\dub.d(655): No package pegged was found matching the dependency ~master
Server: 



extensionHost.ts:293 [Extension Host] WorkspaceD Debug: Server: object.Exception@C:\D\dmd2\windows\bin\..\..\src\phobos\std\getopt.d(881): Missing value for argument -I.


Server: ----------------



extensionHost.ts:293 [Extension Host] WorkspaceD Debug: Server: 0x00406367


Server: 0x004E070A



extensionHost.ts:293 [Extension Host] WorkspaceD Debug: Server: 

extensionHost.ts:293 [Extension Host] DCD is ready
extensionHost.ts:293 [Extension Host] Loaded completions for 0 import paths

**Comment by WebFreak001** [comment]
no that's me, it's the stacktrace. Try compiling workspace-d yourself in debug mode (without release flags) and then send the stacktrace again

**Comment by WebFreak001** [comment]
please try again with code-d 0.21.0 and with that the automatically downloaded newest serve-d version or create a new issue if it still happens
