### ISSUE TITLE
Microsoft Visual C++ Runtime Library Error

### ISSUE THREAD

**Issue by SrMordred** [Pure-D/code-d#125]
_Windows 10
DMD32 D Compiler v2.073.1
VSCode Last Version._

This error show randomly (but constantly) when I build my project:

```
Microsoft Visual C++ Runtime Library

Runtime Error!

Program: C:\D\dmd2\windows\bin\dmd.exe

R6016
 - not enough space for thread data
```

This error shows in my two workplaces, and only using vscode. (Never saw this before with manual building or when using similar plugin on sublime for eg.)

**Comment by WebFreak001** [comment]
uhh seems like I don't allocate enough stack memory in some thread. How much RAM do you have?

**Comment by SrMordred** [comment]
8GB, 65% occupied when the error occur.

**Comment by WebFreak001** [comment]
didn't change anything but never reproduced, reopen if still happening after fresh compilation of everything
