### ISSUE TITLE
Can't switch ArchType to x86_mscoff on windows

### ISSUE THREAD

**Issue by Heromyth** [Pure-D/code-d#126]
The DUP support  architecture type of x86_mscoff on windows, see https://code.dlang.org/packages/libuid.
However, I can't set it in Visual Studio Code using code-d.

**Comment by WebFreak001** [comment]
Fixed in workspace-d ~master now, build from source if you want the feature already, otherwise it might still take a while because I still want to make the module manager and the serve-d implementation
