### ISSUE TITLE
Some ideas + Issues

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/code-d#128]
**Issues:**

* Hints like "Public declaration 'xxx' is undocumented." only show up IF the opened file has been modified and saved. For some reason the open file is never run past dmd until its saved.

* Those same hints seems to constantly report messages like "Loading", despite the hint is already cached.

Open File, Modify and Save. Hold mouse arrow over function. Hint loads first time. Move mouse away. Move back to function. Hint shows up but it will also show "Loading" for a second below.

**Enhancements:**

* Rust like Doc integration. See the Rust plugin. It works exceptionally well showing the function information + Example.

* Add information to the Code-d Plugin its Changelog. Nothing more strange to see the VSC internal changelog for the plugin being empty. That makes it unclear what the changes are when updated.

**Comment by WebFreak001** [comment]
Hm I guess my PR to allow stdin in the checker has been in for quite a while now so I can probably depend on the latest stable version to allow live updates of things like undocumented functions.

Not quite sure why you see loading if there is the hint already, especially that can't even happen on diagnostics. The loading message you see is probably from the documentation lookup which is basically exactly what you point out in point 3.

Well I have been updating the changelog usually but I forgot to do last version because of a big rewrite in the serve-d branch which will soon replace the master branch.

**Comment by Wulfklaue** [comment]
Different installation ( Mobile one at work with VS 12.2 ) and there nothing shows up in regards to hinting. "Simply loading" and a null responds in the console.

`[Extension Host] vscode-icons is active!
extensionHost.ts:285 [Extension Host] Initialized code-d
extensionHost.ts:285 [Extension Host] workspace-d version: 2.10.0
extensionHost.ts:285 [Extension Host] dscanner version: v0.4.0
extensionHost.ts:285 [Extension Host] dfmt version: 0.5.0
extensionHost.ts:285 [Extension Host] dub version: DUB version 1.0.0, built on Jun 20 2016
extensionHost.ts:285 [Extension Host] DCD version: v0.9.0-alpha6
extensionHost.ts:285 [Extension Host] dub is ready
extensionHost.ts:285 [Extension Host] DScanner is ready
extensionHost.ts:285 [Extension Host] Dfmt is ready
extensionHost.ts:285 [Extension Host] DlangUI is ready
extensionHost.ts:285 [Extension Host] Importer is ready
extensionHost.ts:285 [Extension Host] Configuration: true
extensionHost.ts:285 [Extension Host] ["j:\dlangProject\test\source\"]
extensionHost.ts:285 [Extension Host] WorkspaceD Debug: Config files stored in ["C:\\Users\\xxx\\AppData\\Local\\workspace-d", "C:\\ProgramData\\workspace-d"]
Server: 
extensionHost.ts:285 [Extension Host] WorkspaceD Debug: Server: object.Exception@C:\D\dmd2\windows\bin\..\..\src\phobos\std\getopt.d(881): Missing value for argument -I.

Server: ----------------
Server: 0x00405DFF
extensionHost.ts:285 [Extension Host] WorkspaceD Debug: Server: 0x00903868
extensionHost.ts:285 [Extension Host] WorkspaceD Debug: Server: 
extensionHost.ts:285 [Extension Host] DCD is ready
extensionHost.ts:285 [Extension Host] Loaded completions for 1 import paths
2J:\PortableApps\VSCodePortable\App\VSCode\resources\app\node_modules\vscode-textmate\release\main.js:2400 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping
scanNext @ J:\PortableApps\VSCodePortable\App\VSCode\resources\app\node_modules\vscode-textmate\release\main.js:2400
_tokenizeString @ J:\PortableApps\VSCodePortable\App\VSCode\resources\app\node_modules\vscode-textmate\release\main.js:2290
Grammar._tokenize @ J:\PortableApps\VSCodePortable\App\VSCode\resources\app\node_modules\vscode-textmate\release\main.js:2061
Grammar.tokenizeLine2 @ J:\PortableApps\VSCodePortable\App\VSCode\resources\app\node_modules\vscode-textmate\release\main.js:2031
e.tokenize2 @ TMSyntax.ts:301
t._updateTokensUntilLine @ textModelWithTokens.ts:345
(anonymous) @ textModelWithTokens.ts:312
t._withModelTokensChangedEventBuilder @ textModelWithTokens.ts:156
t._revalidateTokensNow @ textModelWithTokens.ts:275
(anonymous) @ textModelWithTokens.ts:249
extensionHost.ts:285 [Extension Host] [Guides] Sending usage statistics...
extensionHost.ts:285 [Extension Host] [Guides] Error while sending usage statistics: Error: getaddrinfo ENOTFOUND api.digitalparticle.com api.digitalparticle.com:80
extensionHost.ts:285 [Extension Host] [Guides] Usage statistics will retry in the next 5 minutes
extensionHost.ts:285 [Extension Host] provideHover
4extensionHost.ts:285 [Extension Host] object
extensionHost.ts:285 [Extension Host] resolve null
extensionHost.ts:285 [Extension Host] provideHover
extensionHost.ts:285 [Extension Host] resolve null
extensionHost.ts:285 [Extension Host] provideHover
extensionHost.ts:285 [Extension Host] resolve null
extensionHost.ts:285 [Extension Host] provideHover
extensionHost.ts:285 [Extension Host] resolve null
extensionHost.ts:285 [Extension Host] provideHover
extensionHost.ts:285 [Extension Host] resolve null`

This seems to be the some interesting part:

object.Exception@C:\D\dmd2\windows\bin\..\..\src\phobos\std\getopt.d(881): Missing value for argument -I.

After some searching i found the reason:

There was some unused test code in the project ( simply a string with some random text that i left behind yesterday to mark some part ). With the error inside the code, it simply resolved to null but did not show the error. Only when removing the error and resaving, the hinting showed up again.

Odd ... kind of fragile behavior. This is not exactly great because anybody with a bad data sets will assume the plugin is broken, when in reality there was a error in the form.

And of course the documentation loading bug from the original post was still active.  *grumble* *grumble*  ;)

**Comment by WebFreak001** [comment]
Uh I fixed that issue once, it was either something with the workspace/dub or with DCD, I can't really remember anymore. Try updating DCD and removing all dependencies and then readding them one by one

**Comment by WebFreak001** [comment]
Files are now linted when opening them, loading issue should be fixed
