### ISSUE TITLE
Make diagnostic messages more noticeable 

### ISSUE THREAD

**Issue by Vild** [Pure-D/code-d#132]
Diagnostic messages should **SCREAM** to your eye, so you can't miss them. (Should probably be a setting)
![http://i.definewild.se/6214](http://i.definewild.se/6214)
The squiggly underline for `worstC2Latency` is super easy to miss. (Especially with this color theme)

**Comment by WebFreak001** [comment]
that's basically the only way to integrate into the diagnostics panel and it is the standardized way. Report to the vscode repository if it isn't noticable enough
