### ISSUE TITLE
Option to disable dfmt.

### ISSUE THREAD

**Issue by Soulsbane** [Pure-D/code-d#133]
I don't think I've overlooked an option to disable dfmt. At the moment I don't have dfmt(nor do I plan to) installed and everytime vscode is started I get a message about it not being found. Is there a way to disable this? Apologies if I've overlooked it! Thanks!

**Comment by WebFreak001** [comment]
hm right, you can disable it but it won't get rid of the error message.

**Comment by WebFreak001** [comment]
dfmt is no longer required now
