### ISSUE TITLE
Error closing vscode: Bad file descriptor

### ISSUE THREAD

**Issue by damianday** [Pure-D/code-d#135]
Running vscode 1.14.1
code-d version: 0.16.2
Windows 10 x64

Please see the attached screenshot:
![err](https://user-images.githubusercontent.com/1334173/28436693-c5ca0e4e-6d8f-11e7-86cc-26779becc651.png)

**Comment by damianday** [comment]
Developer log console output follows..

C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2431 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping
scanNext @ C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2431
extensionHost.ts:320[Extension Host] Initialized code-d
extensionHost.ts:320[Extension Host] workspace-d version: 2.10.0
extensionHost.ts:320[Extension Host] dscanner version: v0.4.0

extensionHost.ts:320[Extension Host] dfmt version: 0.5.0

extensionHost.ts:320[Extension Host] DCD version: v0.9.0

extensionHost.ts:320[Extension Host] dub version: DUB version 1.4.0, built on Jul 19 2017

extensionHost.ts:320[Extension Host] dub is ready
extensionHost.ts:320[Extension Host] DScanner is ready
extensionHost.ts:320[Extension Host] Dfmt is ready
extensionHost.ts:320[Extension Host] DlangUI is ready
extensionHost.ts:320[Extension Host] Importer is ready
extensionHost.ts:320[Extension Host] Configuration: true
extensionHost.ts:320[Extension Host] Array[6]
extensionHost.ts:320[Extension Host] WorkspaceD Debug: Config files stored in ["C:\\Users\\damia\\AppData\\Local\\workspace-d", "C:\\ProgramData\\workspace-d"]
Server: 

extensionHost.ts:320[Extension Host] WorkspaceD Debug: Server: object.Exception@D:\dlang\dmd2\windows\bin\..\..\src\phobos\std\getopt.d(881): Missing value for argument -I.


Server: ----------------
Server: 0x00406383
Server: 0x004E060A

extensionHost.ts:320[Extension Host] WorkspaceD Debug: Server: 

extensionHost.ts:320[Extension Host] DCD is ready
extensionHost.ts:320[Extension Host] Loaded completions for 6 import paths

**Comment by WebFreak001** [comment]
did you update workspace-d yet? i think that was fixed in the latest release

**Comment by damianday** [comment]
No I've only used the version which comes by default with the extension
from the market place, I will report back after trying your suggestion,
thanks.

**Comment by damianday** [comment]
Updating workspace-d to 2.11 has resolved this issue, thanks!
