### ISSUE TITLE
Hover Documentation Improvements

### ISSUE THREAD

**Issue by JinShil** [Pure-D/code-d#136]
The hover documentation window that appears when hovering over a symbol is too narrow causing the documentation to be prematurely wrapped.  In addition, the font appears to be fixed width exacerbating the effect.  

![hover](https://user-images.githubusercontent.com/6023641/28621331-8e261e7c-724b-11e7-824d-9b394874b2e1.png)

My suggestion is to increase the width of the window slightly (or make it a setting), and change the font to a variable-width font (or again, make it a setting).

Not sure if this is a VSCode thing or a code-d thing, though.

**Comment by WebFreak001** [comment]
I don't know why the wrapping appears but I planned on displaying the docs more properly using markdown

**Comment by JinShil** [comment]
The premature wrapping appears simply because the window is too narrow.  But then you see how, not only does it wrap, but it also breaks with every newline in the documentation comment.

![hover](https://user-images.githubusercontent.com/6023641/28623286-7438870c-7250-11e7-830e-814c4f1a44a2.png)

**Comment by WebFreak001** [comment]
But why is it wrapping up there on the equivalent to `write args, '\
')`? Oh probably because of the \n

**Comment by JinShil** [comment]
> Oh probably because of the \n

Yeah, that's weird.  And or some reason it kept the preceding backslash.

**Comment by WebFreak001** [comment]
Note that this is only available in the `serve-d` branch right now
