### ISSUE TITLE
Saving a file causes project and all of it's dependencies to recompile

### ISSUE THREAD

**Issue by TETYYS** [Pure-D/code-d#137]
It should compile only the project the modified files are in. Also, code-d leaves an idle dscanner process after each save

**Comment by WebFreak001** [comment]
the recompilation is done to give compiler errors inside the code file, you can disable it with `"d.enableDubLinting": false` for large projects in your workspace settings. It is basically only running dub build and I tried to set all flags to skip dependency checks so it should only recompile the project, but I can check again and see if there are any other flags. If you find any setting for in the dub api (dub as a package) you can also make a PR against workspace-d implementing it, the code for this is here: https://github.com/Pure-D/workspace-d/blob/master/source/workspaced/com/dub.d#L348

The zombie dscanner process should have been fixed if you manually update your workspace-d to the latest version https://github.com/Pure-D/workspace-d/releases.

**Comment by TETYYS** [comment]
I pulled of workspace-d of git where last commit reads "bump to 2.11.0 (ignore previous release)".

Why use some kind of interface on dub instead of spawning process of dub itself? Running `dub build` regularly doesn't compile already compiled dependencies.

**Comment by WebFreak001** [comment]
well we use the dub library to fetch project import paths and stuff instead of manually parsing the config, so we also just put in dub build because it doesn't need to reparse all the configs every time then which should make it lint faster

**Comment by WebFreak001** [comment]
fixed with serve-d 0.5.0
