### ISSUE TITLE
Must build application at least once in DUB before code-d works

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#14]
If you create a new project using Dub, i.e. dub init -f json -t minimal, add a dependency to dub.json and then open the folder in vscode followed by opening app.d, code-d complains that it cannot find the dependency (Gtkd in my case). Running dub build once from the command line corrects the issue, presumably by creating the .dub folder in the folder.

**Comment by WebFreak001** [comment]
Duplicate https://github.com/Pure-D/workspace-d/issues/5
