### ISSUE TITLE
Wrong binary path for Dscanner.exe

### ISSUE THREAD

**Issue by raVgithub** [Pure-D/code-d#143]
The installator puts this path into user settings
"d.dscannerPath": "SOMEPATH\\.vscode\\extensions\\webfreak.code-d-0.16.2\\bin\\Dscanner\\dscanner.exe"
but the exe after compilation is
"d.dscannerPath": "SOMEPATH\\.vscode\\extensions\\webfreak.code-d-0.16.2\\bin\\Dscanner\\bin\\dscanner.exe". This causes VSCode to not find the dcd and keep trying to install it again.

**Comment by WebFreak001** [comment]
Dup of #100, #130 & fixed in 059c9822d367249f065512e0c53acf9a5cfe428f. The ultimate fix will be when the serve-d branch goes into master and gets published, but right now just update workspace-d and code-d
