### ISSUE TITLE
code-d does not install anymore

### ISSUE THREAD

**Issue by Extrawurst** [Pure-D/code-d#152]
```
Installing into /Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/bin
Removing old version
Removed old version
> git clone --recursive https://github.com/Pure-D/serve-d.git serve-d
Cloning into 'serve-d'...
> dub upgrade
Upgrading project in /Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/bin/serve-d
Root package serve-d reference fluent-asserts ~>0.7.0 cannot be satisfied.
Failed to install serve-d (Error code 2)
```

**Comment by WebFreak001** [comment]
both serve-d and workspace-d compile for me, probably dub doing something weird nobody can predict with some package cache. If you want that undescriptive error message fixed, better bug these people (actually I encourage you and beg you to do so) https://github.com/dlang/dub/pull/1154. Try these commands:
```
$ rm dub.selections.json 
$ dub clean-caches
$ dub clean
Cleaning package at /home/webfreak/Development/serve-d...
$ dub upgrade
Upgrading project in /home/webfreak/Development/serve-d
$ dub build
```

Then you can add the output of `echo $(pwd)/serve-d` into vscode User Settings in the key `"d.servedPath"`

**Comment by Extrawurst** [comment]
Ok I cloned serve-d and did exactly as you said and got the same error. I am on the most recent dub/dmd versions:
```
dub --version
DUB version 1.7.0, built on Jan  2 2018
dmd --version
DMD64 D Compiler v2.078.0
```

btw. workspace-d builds for me too, its only serve-d that is broken

```
dub build
Root package serve-d reference fluent-asserts ~>0.7.0 cannot be satisfied.
```

**Comment by WebFreak001** [comment]
can you try `dub upgrade --vverbose`

**Comment by WebFreak001** [comment]
I just got a fresh clone of serve-d, installed newest dub and dmd and no errors here. Did you maybe manually modify some dub.json in `~/.dub/packages`? Try moving the .dub folder to .dub.old or something like that and then try recompiling. If it works then it is a problem with some modified file because I can't manage to break it with everything I try.

**Comment by Extrawurst** [comment]
wtf - ok wiping out ~/.dub/ fixed it... sorry for the noise

**Comment by WebFreak001** [comment]
maybe dub wrote some garbage in there, do you still have the original? Might report to dub

**Comment by Extrawurst** [comment]
nope I did not save it 🙈

**Comment by WebFreak001** [comment]
ah the issue was workspace-d-master in the dub package folder, dub probably does not try to pull it when upgrading. So for future reference if this happens again, simply delete workspace-d-master in `~/.dub/packages` or `%APPDATA%/dub/packages`
