### ISSUE TITLE
ext:d

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/code-d#157]
Try out the auto suggested extension finder in Visual Studio Code:

```
ext:d
```
You see:
```
D Language 0.9.0
licenser
d-code 0.1.2
d
Dtrace
...
```
No serve-d or code-d.

**Comment by WebFreak001** [comment]
seems impossible to fix

**Comment by WebFreak001** [comment]
vscode seems to finally have picked it up with latest release
