### ISSUE TITLE
Project with target type none. No configurations available and autocompletion could be broken

### ISSUE THREAD

**Issue by deviator** [Pure-D/code-d#158]
I work on complicate project what contains many related parts. Parts are declared as sub packages in main `dub.sdl`. At root of `dub.sdl` I select `targetType "none"`, because it describe relates of sub packages and I have no "main big program". I want to use autocomplite and jumps by `Ctrl+LMB` on declarations, but have this **info** message "No configurations available for this project. Autocompletion could be broken!".

In developer console I found that dub fails to describe `none` package:
```
[Extension Host] WorkspaceD Debug: object.Exception@../../.dub/packages/dub-1.2.0-rc.1/dub/source/dub/project.d(819): Target type is 'none'. Cannot list build settings.
----------------
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x942621]
??:? immutable(char)[][] dub.project.Project.formatBuildSettingPlain!("importPaths").formatBuildSettingPlain(dub.platform.BuildPlatform, immutable(char)[][immutable(char)[]], dub.description.ProjectDescription) [0x9d8bd9]
??:? immutable(char)[][]
...
```

`workspace-d` must use `1.7.0` as minimal version of dub (found [here](https://github.com/Pure-D/workspace-d/blob/master/dub.json#L10)) and I have no `dub` package in `.dub/packages`. Was it fix in new version of `dub`?

And I don't understand where did `workspace-d` binary come from. All other parts are downloaded as sources and builds locally and I can rebuild they by myself. It can be solved as manually download `workspace-d` from git, build and replace binary in `.vscode/extension....` path, but I think exists a more idiomatic way.

installed soft:
vscode: 1.20.1
dub: 1.7.2
code-d: 0.16.3
ldc2: 1.8.0-beta1
dmd: v2.078.3

OS: x86_64 fedora 26 4.14.16

**Comment by WebFreak001** [comment]
the workspace-d is precompiled because it was a problem on too many devices to compile it from scratch due to the 2GB memory usage. I will need to release a new workspace-d binary for this or you have to compile it yourself like you did

**Comment by deviator** [comment]
Unfortunately new version of `dub` have same problem
`../../../.dub/packages/dub-1.7.2/dub/source/dub/project.d(846): Target type is 'none'. Cannot list build settings`

**Comment by deviator** [comment]
https://github.com/dlang/dub/blob/master/source/dub/project.d#L846
`targetType "none"` directly not allowed in this function. I don't understand why. No more ways to do what do `formatBuildSettingPlain`?
