### ISSUE TITLE
Could not initialize dub. Falling back to limited functionality! Since dmd2079 and dub 1.8.0

### ISSUE THREAD

**Issue by ArjanKn** [Pure-D/code-d#162]
This severely limits the usability of the plugin.
statusbar button for:
- configuration
- archtype
- buildtype
- compiler
all stay empty

**Comment by WebFreak001** [comment]
workspace-d or serve-d?

**Comment by ArjanKn** [comment]
Serve-d.

Some more details:
the problem only occurs as soon as there are dependency in dub.json of
dub.sdl file.

Op 20 mrt. 2018 8:36 a.m. schreef "Jan Jurzitza" <notifications@github.com>:

**Comment by WebFreak001** [comment]
try pulling and recompiling serve-d, there have been some updates. (Also do dub upgrade or even move/delete the workspace-d cache in `.dub/packages` to make sure workspace-d gets compiled)

**Comment by ArjanKn** [comment]
Seems the issue is due to dub-1.8.0 having the packages in AppData/Local where previous had the packages in AppData/Roaming ... (On windows)

**Comment by WebFreak001** [comment]
hm yes if you update both dub and serve-d everything should work again
