### ISSUE TITLE
Windows 10 64bit: code-d not started after installed: workbench.main.js:2869 [webfreak.code-d]Channel has been closed

### ISSUE THREAD

**Issue by dangbinghoo** [Pure-D/code-d#172]
installing the code-d plugin has error for starting: channel has been closed.
```
Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] Error: Channel has been closed
```
the verbose error info was attached.
[-1523201261806.log](https://github.com/Pure-D/code-d/files/1887606/-1523201261806.log)

**Comment by WebFreak001** [comment]
did serve-d successfully download? Try manually calling `<path to serve-d> --version`, check your user settings for the path (should be in `%APPDATA%/code-d/bin/serve-d`)
