### ISSUE TITLE
Please avoid node dependency to "natives" module

### ISSUE THREAD

**Issue by bpasero** [Pure-D/code-d#175]
Hi,

I am a developer on VSCode and wanted to reach out to inform you that this extension is either using or having a dependency to a node module "[`natives`](https://www.npmjs.com/package/natives)" that will soon no longer be supported in VSCode once we updated to node.js 8.x (as part of our Electron 2.0 update which is planned for the near term). 

The full graph is:

```
└─┬ unzip@0.1.11
  └─┬ fstream@0.1.31
    └─┬ graceful-fs@3.0.11
      └── natives@1.1.0 
```

It would be great if this dependency could be avoided by either not depending on it anymore or updating the dependencies to newer versions so that this module is no longer pulled in. 

As soon as any code in your extension (including `node_modules`) calls `require("natives")` we will throw an exception to prevent this module from getting loaded.

If this is just a `devDependency` and the module is never loaded in production, then you can ignore this issue and just close it!

More details in https://github.com/Microsoft/vscode/issues/47569

Thanks!
Ben
VSCode Team

**Comment by WebFreak001** [comment]
didn't test this on windows but if it doesn't work I'm sure someone will eventually complain.

**Comment by bpasero** [comment]
@WebFreak001 thanks 👍
