### ISSUE TITLE
dfmt stops working when dfmt.braceStyle != "allman"

### ISSUE THREAD

**Issue by spikespaz** [Pure-D/code-d#176]
`dmnt` just straight up stops working when I try to set `"dfmt.braceStyle": "ratliff"`.

The default, `allman`, works fine.

I'm trying to use the values given on the linked [Wikipedia article](https://en.wikipedia.org/wiki/Indentation_style#Ratliff_style).

**Comment by 0xEAB** [comment]
`ratliff` is not supported by dmft.
Currently implemented: `allman`, `otbs`, or `stroustrup`.

https://github.com/dlang-community/dfmt#dfmt-specific-properties

**Comment by WebFreak001** [comment]
Oh yeah the description of the key is probably confusing! https://github.com/Pure-D/code-d/blob/master/package.json#L371
