### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by jacob1237** [Pure-D/code-d#177]
Hey,

After installing the latest version of the library (which is 0.17.2 for the moment), I got really weird syntax highlighting issues (I'm using the Monokai theme)

First of all, imports are orange now. Not sure sure if that's good or bad, but it looks weird:
![import](https://user-images.githubusercontent.com/1957938/38772975-9ba99460-404b-11e8-9957-c72da303efc8.png)

Debug statement is completely broken (the same for previous versions, but that's not really critical):
![debug](https://user-images.githubusercontent.com/1957938/38772998-f840025e-404b-11e8-8c44-704a68654cbf.png)

Conditions are broken. They have different colors, and I'm not really sure about the pattern, because it is different for different places: sometimes condition is white, sometimes is orange. Is that how it supposed to work, or it's a bug?

Second, boolean identifiers are not highlighted (previous versions worked just fine):
![if_else_bool](https://user-images.githubusercontent.com/1957938/38773008-1aa022a2-404c-11e8-9d11-cdc7e7bce409.png)

Comparing to `dlang-vscode` extension, syntax highlighting looks really really weird and broken.
Is it something wrong with my setup, or it's a bug?

Thanks,
Jacob

**Comment by jacob1237** [comment]
BTW, `in` operator has different highlighting in different situations.

`in` inside a condition:
![in_inside](https://user-images.githubusercontent.com/1957938/38773335-43fd7478-4052-11e8-98cc-be18c8721c68.png)

and standalone (no highlighting):
![in_outside](https://user-images.githubusercontent.com/1957938/38773341-515916c2-4052-11e8-9643-3662fa708027.png)

**Comment by WebFreak001** [comment]
thanks, yes the grammar has been recently changed to another one, some tweaks are still needed.
