### ISSUE TITLE
[Question] How can I disable DScanner warnings?

### ISSUE THREAD

**Issue by weltensturm** [Pure-D/code-d#178]
Specifically, how can I disable "Public declaration [...] is undocumented"?

I tried adding the result of "Insert default dscanner.ini [...]" to `~/.config/dscanner/dscanner.ini` (on Windows) and setting `undocumented_declaration_check` to `disabled`, but that doesn't seem to have an effect.

**Comment by WebFreak001** [comment]
put the dscanner.ini in your workspace folder, workspace-d uses it there, though it should also read from .config
