### ISSUE TITLE
Build button issues

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#18]
A couple of minor issues with the build button as follows:

* Sometimes the output from the build doesn't appear in the Output window, you have to explicitly toggle the Output view to see it. All I see is the initial build line:

```
> dub build --config=application --build=debug
```

* When you click the build button, the output view appears on the right side as normal. However if you click on a new source file, the new source file opens on the right instead of replacing the one on the left which is what happens when you toggle the output view normally.

**Comment by WebFreak001** [comment]
The second is intended and comes from vscode. Its the way to select in which column files open.

For the second is there any way to always reproduce it?

**Comment by WebFreak001** [comment]
Fixed in new vscode release
