### ISSUE TITLE
Imports format weird

### ISSUE THREAD

**Issue by kasrasadeghi** [Pure-D/code-d#190]
![image](https://user-images.githubusercontent.com/14009618/41828526-6a28641a-77fb-11e8-8106-90f2598f54fc.png)

I don't think there should be a space between every import.

**Comment by WebFreak001** [comment]
there is no space, there is supposed to be an import timing there (you can see that because of the line numbers)

Though why it is broken is a bug. Anyway if you want to disable it, there is a import timing setting you can set to false.

**Comment by kasrasadeghi** [comment]
Do you know what the setting is?

**Comment by WebFreak001** [comment]
`"d.enableDMDImportTiming": false`

**Comment by WebFreak001** [comment]
defaults to false now

**Comment by kasrasadeghi** [comment]
Thanks!
