### ISSUE TITLE
Fails to start serve-D, can't load libphobos2-ldc-shared.so.80

### ISSUE THREAD

**Issue by testing-in-chrome** [Pure-D/code-d#198]
On Ubuntu 16.04, I get the following errors when I updated to the most recent version of the extension:

[Error - 11:36:58 PM] Connection to server is erroring. Shutting down server.
/home/<user>/.local/share/code-d/bin/serve-d: error while loading shared libraries: libphobos2-ldc-shared.so.80: cannot open shared object file: No such file or directory

I already do have ldc2 installed via `sudo snap install --classic ldc2`.

**Comment by jpf91** [comment]
Should be fixed with new DCD binaries.

**Comment by WebFreak001** [comment]
released new executables and even tested it by uninstalling ldc2, should work now
