### ISSUE TITLE
All symbols are listed uniformly without showing which member belongs to which structure in outline feature.

### ISSUE THREAD

**Issue by Soulsbane** [Pure-D/code-d#201]
Images speak louder than words :)
[DLang Outline](https://imgur.com/d33JWFO)
[Javascript Example Outline](https://imgur.com/GCDHaH6)

Hopefully you see what I mean. It isn't a big deal unless you are viewing a rather large module.
Thanks a lot!

**Comment by WebFreak001** [comment]
yes the outline view API is horrible, I don't even know why Microsoft created a second API for it which uses the same information as the symbols list view, but instead of having `parent` values on each item, they have `children` values.

**Comment by Soulsbane** [comment]
That's interesting. No problem. That's about like the Windows API is written! Thanks!
