### ISSUE TITLE
VS Code thinks that a line is a link?

### ISSUE THREAD

**Issue by spikespaz** [Pure-D/code-d#205]
This is the full line:
```
    ushort[] firstVerParts = firstVer.split('.').to!(ushort[]);
```

![image](https://user-images.githubusercontent.com/12502988/44244365-7f68d100-a188-11e8-8358-89fe0347d27a.png)

**Comment by WebFreak001** [comment]
code-d doesn't provide any link parsers. What you are seeing is probably from another extension, try disabling code-d and see if it still happens. If it does try updating vscode and disabling other extensions
