### ISSUE TITLE
Where is run button?

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#208]
When I have used code-d previously there was run and build buttons in the bottom status window next to the compiler switch (i.e. dmd button). I've noticed for awhile now that those buttons are gone, am I missing something in my configuration to bring them back?

Also, when I try using code-d:run from the command palette I get the message " command 'code-d:run' not found".

I've ignored it for awhile but gearing up to do some more serious work and am missing those buttons :)

**Comment by WebFreak001** [comment]
Ctrl-Shift-B, it's integrated into the vscode build tasks now
