### ISSUE TITLE
Dynamically showing compilation errors?

### ISSUE THREAD

**Issue by helikopterodaktyl** [Pure-D/code-d#213]
One of the features mentioned is "Dynamically showing compilation errors by invoking dub without any binary output". How exactly does that feature work?

I tried to create the (almost) simplest possible D program:

`
import std.stdio;

void main()
{
	xyz = 10;
}
`

I expected that xyz would be underlined as "Error: undefined identifier xyz" as it's reported by dmd/dub, but nothing like that happens. Does it need to be enabled somewhere?

**Comment by WebFreak001** [comment]
`"d.enableDubLinting": true` which it should already be by default

It will only work if auto completion also works (or more exactly if dub could be loaded successfully for the project)

Also there was a regression not too long ago breaking this, make sure you have the latest serve-d version

**Comment by helikopterodaktyl** [comment]
Yes, the setting is set to "true". Autocompletion works. I built serve-d manually from latest git commit (cad0258cc2861d70e19a81027f6dc89b663fe4c2) just to be sure, but still nothing. In code-d log I can see "Running dub build", but nothing really comes up after it. DScanner and code completion seem to be working well.

**Comment by helikopterodaktyl** [comment]
Well. I didn't change anything, but it seems to have fixed itself, I am getting "underlines" from DUB now... closing
