### ISSUE TITLE
Request - parse dmd exception output to make it compatible with vscode linkify

### ISSUE THREAD

**Issue by aliak00** [Pure-D/code-d#214]
The exception output format is e.g.

`core.exception.AssertError@tests/optional.d(450): unittest failure`

So vscode cannot recognize it as a file link since there's no file called `core.exception.AssertError@tests` in the cwd.

I wonder if there's anyway code-d can help out here?

**Comment by WebFreak001** [comment]
good idea I can add a link provider but I don't know if it will work for the embedded console

**Comment by aliak00** [comment]
Awesome! Fingers crossed ! And FYI opened this issue for DMD as well -> 
https://issues.dlang.org/show_bug.cgi?id=19254

**Comment by WebFreak001** [comment]
I bet that won't go through though because it will break compatibility with programs (code-d included)

**Comment by aliak00** [comment]
Aww :( well if it doesn’t then it doesn’t. Out of curiosity how would it
break code-d?

**Comment by WebFreak001** [comment]
uh well after looking into it, it was actually compiler errors which I parsed so this wouldn't really be affected after all

**Comment by WebFreak001** [comment]
there is now a proposed API in VSCode insiders so I am finally able to do this: https://code.visualstudio.com/updates/v1_47#_terminal-link-provider

It might still change and won't be usable for normal users at least before 1.48 though.
