### ISSUE TITLE
"Go to definition" doesn't work for "public imported" symbols

### ISSUE THREAD

**Issue by helikopterodaktyl** [Pure-D/code-d#218]
"Go to definition" doesn't work for symbols which were imported with "public import" feature. For example: module C implements class Foo. Module B public imports module C. Module A imports module B. As a result, class Foo is accessible from module A. However, code-d is unable to follow from module A to the original definition in module C.

**Comment by WebFreak001** [comment]
works here, which DCD version is code-d running? (Search for `Detected dcd-client` in the output log)

```d
module a;

import b;

void test()
{
	foo();
}
```

```d
module b;

public import c;
```

```d
module c;

void foo()
{
}
```
