### ISSUE TITLE
dub: run task fails on new dub project

### ISSUE THREAD

**Issue by aliak00** [Pure-D/code-d#219]
Just created a new dub project and hit Cmd+shift+P, then chose the `dub: Run project` task and the output in the terminal is:

```
Executing task: dub run --compiler=dmd -a=x86_64 -b=debug -c= <

Error processing arguments: Missing value for argument -c=.
Run 'dub help' for usage information.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Seems like `-c` is expeccted from somewhere. My dub.json is:

```
{
	"name": "dsampler",
	"authors": [
		"Ali Akhtarzada"
	],
	"dependencies": {
		"kafka-d": "~>0.0.5"
	},
	"description": "A minimal D application.",
	"copyright": "Copyright © 2018, Ali Akhtarzada",
	"license": "proprietary"
}
```

**Comment by WebFreak001** [comment]
Can you try if this also happens with latest serve-d if you set `d.betaStream` to `true`? In the older version it should work after doing `dub upgrade` and then reloading vscode.

**Comment by aliak00** [comment]
Got it working after reinstalling code-d 👍:
`> Executing task: dub run --compiler=dmd -a=x86_64 -b=debug -c=application <`

When I just changed `d.betaStream` to true (I wasn't sure what to dub upgrade) it didn't work. So I reinstalled code-d. When I reinstalled it the betaStream setting was still true. So I'm not sure if that was it. I disabled it now and it's still ok but I guess it doesn't roll back to the non-beta commit?

**Comment by WebFreak001** [comment]
it should only upgrade to newer stable releases if you set betaStream to false again.

**Comment by benjaminfichet** [comment]
Hi guys, 
I've got the same problem.
```
> Executing task: /home/ben/dlang/dmd-2.083.1/linux/bin64/dub run --compiler=/home/ben/dlang/dmd-2.083.1/linux/bin64/dmd -a=x86_64 -b=debug -c= <

Error processing arguments: Missing value for argument -c=.
Run 'dub help' for usage information.
The terminal process terminated with exit code: 1
```
Using the same command without the -c=. does the trick
```
 ~/dlang/dmd-2.083.1/linux/bin64/dub run --compiler=~/dlang/dmd-2.083.1/linux/bin64/dmd -a=x86_64 -b=debug
```

I tried what aliak did with no luck : 
```
Set d.betaStream to true, restart, same error
Set d.betaStream to false, restart, same error
Set d.betaStream to true, reinstall code-d, same error
Set d.betaStream to false, same error
```

Note that I'm not using tools downloaded by code-d directly but environments installed by D's install.sh

**Comment by WebFreak001** [comment]
the issue happens when dub fails to initialize or isn't initialized yet. Does autocompletion work properly? Try `dub upgrade` and then reload vscode
