### ISSUE TITLE
```json  { 	"activationTimes": { 		"startup": true, 		"codeLoadingTime": 417, 		"activateCallTime": 15, 		"activateResolvedTime": 0, 		"activationEvent": "workspaceContains:dub.json" 	} } ```

### ISSUE THREAD

**Issue by gaoxincheng** [Pure-D/code-d#226]
- Extension Name: code-d
- Extension Version: 0.19.0
- OS Version: Windows_NT x64 10.0.10586
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by WebFreak001** [comment]
Please add a description what's wrong and what you expected
