### ISSUE TITLE
dub upgrade wizard

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/code-d#230]
"Could not update import paths" or "Could not upgrade dub project" should offer the user a button to interactively solve the issue.

A command line with "dub upgrade" in the affected project should be run.
Reload import paths should automatically be run afterwards
If still broken, offer to create an issue on the repo

**Comment by WebFreak001** [comment]
for now the following things are being done and are deemed enough:
- verify syntax of dub recipe before loading it
- don't try to load if dub didn't start properly

fixes most issues for now, tests coming in separate push

**Comment by munael** [comment]
I'm facing this issue in Jan 2024:

```
2024-01-03T03:02:42.187 [info] source\served\commands\dub.d:228:onDidSaveDubRecipe Updating dependencies
2024-01-03T03:02:[progress] [01224.285] [importUpgrades] 0 / 10: file:///<path to repo>
42.187 [warning] lsp\source\served\lsp\jsonrpc.d:400:showMessage error message:  Could not upgrade dub project
```

Let me know if I can provide other data.

**Comment by WebFreak001** [comment]
Try upgrading to serve-d nightly by setting the `d.servedReleaseChannel` setting in vscode (Ctrl-, for User Settings) to `nightly` - afterwards, reload the window with `Ctrl-Shift-P` -> `Reload Window` and let it automatically download the update.

Otherwise open a new issue.
