### ISSUE TITLE
endless defunct dcd-client's

### ISSUE THREAD

**Issue by yannick** [Pure-D/code-d#24]
i'm getting gazillion of defunct dcd-client's on linux up to a point where i cant run dub anymore since i reached the max number of processes.

**Comment by WebFreak001** [comment]
did you update workspace-d and code-d? This was fixed weeks/months ago

**Comment by yannick** [comment]
my install was after the fix, but i upgraded both now again (workspace-d was behind 1 commit).

**Comment by WebFreak001** [comment]
If this still happens please open another issue on the workspace-d project
