### ISSUE TITLE
No user-guide

### ISSUE THREAD

**Issue by dejlek** [Pure-D/code-d#240]
It would be really good if you could provide a step-by-step guide for people who never used VSCode before how to create a tiny D project, build and debug it in VSCode... Perhaps with some typical project structure, and good practices.

**Comment by WebFreak001** [comment]
good idea. I will dump a few of my thoughts what should be included here:

- [ ] automatically open as rendered HTML document once at startup for all new users
- [ ] tell user that changelog of code-d always shows new features, also implement and have a checkbox in this welcome dialog to enable showing changelogs after every code-d update
- [ ] it should tell the user step by step for the most basic setup for an app (using Create Project command which will create a dub project)
- [ ] links to GitHub, discord
- [ ] Tell user that if something is stuck, a window reload might fix it.

**Comment by dejlek** [comment]
I had a massive headache yesterday trying to figure out how to setup the configuration so that I can build a "hello world" application with VSCode + code-d plugin. I think that should be included in the User Guide as that is absolutely essential (if you can't build properly your D application inside VSCode, then what's the point).

**Comment by WebFreak001** [comment]
Yeah it should probably contain something like

Use the command palette (Ctrl-Shift-P or F1) to search for commands. You can open any dub project in vscode or use the "code-d: Create Project" command to start a new project from a template.

code-d ships with default build tasks for dub projects inside the vscode build window (Ctrl-Shift-B) which you can use to build and run your project using a shortcut. Once you added such a build task you can also reference to them inside a debug configuration to build your project before debugging.

If you use a custom project structure without dub you will have to invoke your own build script from the build tasks. If code-d is missing import paths for the auto completion, adjust your workspace or folder settings and manually insert all your projects import paths like `"d.extraRoots": ["module1/source", "module2/source", ...]`

**Comment by 564064202** [comment]
Dlang lacks a good IDE,and code-d is a good IDE.
But I can't config it well in a week on linux(I can't debug and I don't how to config it).
I think everybody want to use Dlang will come across this problem,so
I suggest you give us a detail help document.

**Comment by 564064202** [comment]
I'm so sorry ,I will drop dlang,for there is not a good Ide

**Comment by PetarKirov** [comment]
@564064202 A true hacker shouldn't need an IDE :P

**Comment by 564064202** [comment]
@PetarKirov NO,Project needs

**Comment by WebFreak001** [comment]
this is being started in the wiki now, first page is up: https://github.com/Pure-D/code-d/wiki/Installing-Code-D

Some more usage tips and such are gonna follow
