### ISSUE TITLE
Enhancement: format selection

### ISSUE THREAD

**Issue by jblachly** [Pure-D/code-d#241]
Presently, the format document keybinding runs dfmt, but the format selection keybinding does not function.

I looked thru the code-d codebase and unfortunately could not figure out how you've bound the formatting function to the keybinding.

I did find this documentation on the API for format selection (format range), HTH:

https://github.com/Microsoft/vscode/blob/984a3a17a749925b3e19fedbd93222d1ccbc13c4/src/vs/vscode.d.ts#L3013

**Comment by WebFreak001** [comment]
format selection is not implemented because it's quite a bit more difficult to implement than a whole document formatting where you know about everything. I don't think this will be implemented in the near future either, instead you could always format everything.

**Comment by ZombineDev** [comment]
BTW, I think DLS has format selection feature. The way it works is by formatting the whole document in a temporary buffer and then replacing only the selection in the original document.

**Comment by WebFreak001** [comment]
merged in with #120
