### ISSUE TITLE
Can't compile from source if dmd isn't installed on windows

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/code-d#242]
If on windows, we try to build with
```
dub build --arch=x86_mscoff
```

however if dmd isn't installed (and only ldc is installed), then it will fail with
```
> dub build --arch=x86_mscoff
Unsupported architecture: x86_mscoff
Failed to install serve-d (Error code 2)
```

We already check if a compiler is available on startup, caching this and changing the build settings depending on available compilers should easily work. Otherwise checking the output for "unsupported architecture" on failure should be a good enough solution.

**Comment by Ezneh** [comment]
I still get the error if ldc comes before dmd in the PATH environment variable.
Works otherwise if dmd comes before ldc.

**Comment by WebFreak001** [comment]
the new release isn't published on the marketplace yet

**Comment by Ezneh** [comment]
I'm updating with the betaStream option, so it should have worked then ?

**Comment by WebFreak001** [comment]
no this install issue was a code-d issue, betaStream just gives you the latest serve-d (language server), but not the latest code-d (vscode extension)

**Comment by Ezneh** [comment]
Oh alright, didn't know that. Thanks for the clarification.
