### ISSUE TITLE
DCD install fail (certificate problem)

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/code-d#244]
This is what I get!

```
Installing DCD
Downloading from https://github.com/dlang-community/DCD/releases/download/v0.10.2/dcd-v0.10.2-windows-x86.zip to C:\Users\Danol\AppData\Roaming\code-d\bin
Failed installing: std.net.curl.CurlException@std\net\curl.d(4340): Peer certificate cannot be authenticated with given CA certificates on handle F33008
```

**Comment by CZDanol** [comment]
I've tried downloading and extracting the file to the folder manually, still getting this message.

**Comment by WebFreak001** [comment]
Fixed in serve-d https://github.com/Pure-D/serve-d/commit/dc23cfa469ac825308be199fdcb796e335f75f3c and https://github.com/Pure-D/serve-d/commit/7e91c62211b125b9ec1674aafb08ab6a393bf94f (both download and letting extension extract)

**Comment by CZDanol** [comment]
Thanks

**Comment by veelo** [comment]
I suppose you need to tag a new release before this starts working? Is there anything else users need to do in Visual Studio Code, like uninstalling+reinstalling code-d? Does it need a version bump too?

Thanks.

**Comment by WebFreak001** [comment]
serve-d will need a new release tag and code-d will need to bump to that release tag and get tagged itself.

You can add `"d.betaStream": true` in your user settings to make it pull from master where it should work already though.

**Comment by veelo** [comment]
> You can add `"d.betaStream": true` in your user settings to make it pull from master where it should work already though.

Great tip! File->Preferences->Settings->User Settings->Extensions->D configuration->Beta Stream

Somehow a corrupt `dcd-v0.10.2-windows-x86.zip` was till available at `C:\Users\<user>\AppData\Roaming\code-d\bin` (zero bytes), probably from a previous failed download. It decided to try and install that one first but obviously failed and then gave up. After removing the file and restarting VSC, installation succeeded.

It would probably be helpful if failed installation of existing zip were detected and retried on a fresh download.

**Comment by andrej-mitrovic-sociomantic** [comment]
Any update for a release to be made?

**Comment by WebFreak001** [comment]
uh that's a good idea haven't done one for some time now. I will do one soon.
