### ISSUE TITLE
New snippets

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/code-d#245]
I think it's time to update [old snippets](https://github.com/Pure-D/code-d/blob/master/snippets/d.json) and add new useful ones. Everyone who wants to contribute, please comment with all the snippets you would want to use. They should be small and either be general purpose or do common boilerplate code in normal D code. You can also suggest snippets for dub.json, dub.sdl, vibe.d .dt files, dlangui .dml files, etc.

First of all these are the snippets I actively use a lot or think are useful: (I recommend you list what you like to use aswell)
- `main`
- `refp`
- `gets`
- `op*`
- `ex` - but could be improved
- `inrange` <--
- `fwrange` <-- my 2 favorite ones

Here are some I start with: (`<>` denotes an editable cursor)

`imain`
```d
int main(string[] args) {<>}
```

`cmain` - `-betterC main`
```d
extern (C) void main() {<>}
```

`cimain` - `-betterC main`
```d
extern(C) int main(int argc, const(char)** argv) {<>}
```

`typedef` - `Creates a typesafe alias not allowing implicit casting from base type, but allows implicit conversion to the base type in most cases. Therefore the implicit casting works a lot like class/interface inheritance.`
```d
enum <1:MyType> : <2:BaseType> {<3:init = 0>}
```

`proxy` - `Creates a typesafe alias not allowing implicit casting to the base type, but allows implicit conversion from the base type in most cases. Basically allows copying any base type with new properties and methods as new and separate type. Imports std.typecons : Proxy`
```d
struct <1:MyType> {
	<2:BaseType> base;
	mixin Proxy!base;
}
```

`cominterface` - `Win32 COM interface without implementation to talk to other applications.`
```d
interface <1:MyType> : IUnknown {
extern(Windows):<2>
}
```

`comobject` - `Win32 COM interface with implementation to serve to other applications.`
```d
class <1:MyType> : ComObject {
extern(Windows):<2>
}
```

Range improvements: make them only include methods.
Update `inrange`:
```d
void popFront() {<4:>}
bool empty() @property const {<3:return true;>}
<1:auto> front() @property {<2:return myElement;>}
```

Update `fwrange`:
```d
void popFront() {<5:>}
typeof(this) save() {<4:return this;>}
bool empty() @property const {<3:return true;>}
<1:auto> front() @property {<2:return myElement;>}
```

`infrange`:
```d
enum bool empty = false;
void popFront() {<3:>}
<1:auto> front() @property {<2:return myElement;>}
```

`outrange`
```d
void put(<2:MyElement> item) {<4:>}
```

`birange`
```d
bool empty() @property const {<6:return true;>}
void popFront() {<4:>}
void popBack() {<5:>}
<1:auto> front() @property {<2:return myElement;>}
<1:auto> back() @property {<3:return myElement;>}
```

`randrange`
```d
<1:auto> opIndex(<2:size_t> i) {<3:return myElement;>}
<2:size_t> length() @property const {<4:return 0;>}
<2:size_t> opDollar(size_t pos)() {<5:return length;>}
```

`opslice`
```d
<1:size_t[2]> opSlice(size_t start, size_t end) {<2:return [start, end];>}
<3:auto> opIndex(size_t[2] slice) {<4:return base[slice[0] .. slice[1]];>}
```

Range snippets could maybe even be served by serve-d and automatically analyze which fields already exist and omit or update them accordingly.

diet snippets:
`html`
```diet
doctype html

html(lang="en")
	head
		meta(charset="utf-8")
		meta(name="viewport", content="width=device-width, initial-scale=1")
		title <1:>
	body
		<2:>
```

`css`
```diet
link(rel="stylesheet", href="<>")
```

`js`
```diet
script(src="<>")
```

`style`
```diet
:css
	<>
```

`script`
```diet
:javascript
	<>
```

`markdown`
```diet
:markdown
	<>
```

= diet should also support D snippets inside embedded D code. Another reason to complete them in serve-d =

I suggest renaming some of the existing snippets too:
ex should become exception
er should become error
tmpl should become template
fore should become foreach

Typing whole words are easier to remember and it looks more like keywords are auto-completed.

**Comment by WebFreak001** [comment]
dub.json snippet:
`pkg` - `Minimum information for publishing your package on the dub registry`
```json
{
	"name": "<1:>",
	"description": "<2:>",
	"license": "<3:>",
	"dependencies": {
	}
}
```

dub.sdl snippet:
`pkg` - `Minimum information for publishing your package on the dub registry`
```sdl
name "<1:>"
description "<2:>"
license "<3:>"
```

**Comment by dd86k** [comment]
I never use snippets but

`forea` (`foreach`) and `forer` (`foreach_reverse`) would be decent starts to 
```d
foreach (item; list) {<>}
foreach_reverse (item; list) {<>}
```

Softly respecting D-style, scope should be expanded.

**Comment by WebFreak001** [comment]
foreach already exists as `fore`, but well I now think that this was a bad idea and that it should like use a full word like foreach instead. When you write a word you tend to finish that word and not abort halfway. That applies to people who write fast and already wrote the word before finishing to think, but also for people who write slow and need to look on their keyboard and can't look up to see the auto-completion. I tried to use these snippets myself but the usage could be plotted like cryptic name vs usefulness of the snippet. Foreach is _meh_ with the usefulness so it shouldn't be a very cryptic name.

That in mind, snippets shouldn't use common variable names and really on exclusively try to use keywords, because if you type some common variable name and press enter, it would extend the snippet which would be annoying when you don't want it.

**Comment by dd86k** [comment]
so `foreach` and `foreachr` or `foreach_r` snippets?

**Comment by WebFreak001** [comment]
a little bit experimental, but I think these are common boilerplate to write:

`viberouter` - `inserts a new router instance with GET / path`
```d
auto <1:router> = new URLRouter();
<1:router>.get("/", &<2:index>);
```

`vibeserver` - `inserts a basic vibe.d HTTP server structure`
```d
auto <3:settings> = new HTTPServerSettings;
<3:settings>.port = <1:3000>;
<3:settings>.bindAddresses = <2:["::1", "127.0.0.1"]>;

auto <4:router> = new URLRouter();
<4:router>.get("/", &<5:index>);

listenHTTP(<3:settings>, <4:router>);
```

`vibeget` - `inserts a basic low-level GET request using vibe.d`
```d
requestHTTP(URL("<1:>"), null, (scope HTTPClientResponse res) {
	<2:// TODO: check res.statusCode and read response into parent scope variables>
});
```

`vibegettext` - `inserts a basic low-level GET request using vibe.d reading the full response as text`
```d
string <1:text>;
requestHTTP(URL("<2:>"), null, (scope HTTPClientResponse res) {
	<3:// TODO: check res.statusCode>
	<1:text> = res.bodyReader.readAllUTF8();
});
```

`vibegetjson` - `inserts a basic low-level GET request using vibe.d reading a JSON response`
```d
Json <1:json>;
requestHTTP(URL("<2:>"), null, (scope HTTPClientResponse res) {
	<3:// TODO: check res.statusCode>
	<1:json> = res.readJson(); // TODO: probably want to .deserializeJson!T
});
```

`vibepost` - `inserts a basic low-level POST request using vibe.d`
```d
requestHTTP(URL("<1:>"), (scope HTTPClientRequest req) {
	req.method = HTTPMethod.POST;
	<2:// TODO: write request body>
}, (scope HTTPClientResponse res) {
	<3:// TODO: check res.statusCode and read response into parent scope variables>
});
```
