### ISSUE TITLE
Dscanner checks preview tabs too

### ISSUE THREAD

**Issue by unleashy** [Pure-D/code-d#249]
Before the most recent update, if I ctrl+clicked on a file, dscanner would not lint that file. The tab has an italicised title (like this https://i.imgur.com/IClFr1p.png) which seems like some vscode "preview editor" feature.

But in some recent update that changed and now dscanner lints those files too, which often are external to the project, and the warnings don't go away after closing the tab, which is _extremely_ aggravating (https://i.imgur.com/GY0LDfg.png). What happened?

**Comment by WebFreak001** [comment]
I changed that opening a file would immediately lint instead of waiting for an edit. It should probably not lint external files. I think maybe the problems window should actually show linting stuff for all files and not just opened stuff (but well not for dependencies)

**Comment by unleashy** [comment]
Could there be an option? I really liked that whole "only lint until an edit" thing.

**Comment by WebFreak001** [comment]
ok you can set `"d.lintOnFileOpen": false` with serve-d master (betaStream) now

**Comment by unleashy** [comment]
Thank you!!

**Comment by unleashy** [comment]
@WebFreak001 sorry, but did I do this right? I'm on the beta stream and I have `"d.lintOnFileOpen": false` set in my configurations. I checked the logs and this is the most relevant part:

```
2019-04-15T16:20:29.796:source\served\types.d:config:442 Config for file:///d%3A/Programming/d/emc/source/emc/net.d: const(Configuration)(const(D)(null, "C:\\Users\\unleashy\\AppData\\Roaming\\code-d\\bin\\dcd-client.exe", "C:\\Users\\unleashy\\AppData\\Roaming\\code-d\\bin\\dcd-server.exe", "dub", "dmd", true, true, true, false, true, true, false, false, [], "", "", "", "", true, true, false, true, true, [], [], ask, 4, false), const(DFmt)(true, "otbs", true, true, false, true, true, "conditional_newline_indent"), const(DScanner)([]), const(Editor)([80, 120]), const(Git)("C:\\Program Files\\Git\\cmd\\git.exe"))
```

which, seeing the Configuration.D struct in source/served/types.d, does seem to say that `lintOnFileOpen` is set to false, as expected. However, opening files in a preview tab still activates dscanner. What gives?

**Comment by WebFreak001** [comment]
are you editing the file or something like that? It works as expected for me

**Comment by unleashy** [comment]
Yeah, tried with about 3 different projects, in none of them work. Also, vscode says this about the config, is that supposed to be the case? https://i.imgur.com/cSjGDrv.png

**Comment by WebFreak001** [comment]
it was an issue with default configuration handling. It will now use user settings as default instead of hardcoded values.

Also closing external files will now make diagnostics go away (regardless of this setting)

**Comment by unleashy** [comment]
Yep, it works perfectly now! Thank you so much!
