### ISSUE TITLE
Not using dcanner.ini

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#25]
I have dscanner.ini in my ~/.config/dscanner/dscanner.init directory where I have turned off certain checks. When I run dscanner manually using ```dscanner -S terminal.d``` this ini file is used and I can see my de-selected checks are skipped such as the non-documented public members. However when code-d/workspace-d runs dscanner this ini file doesn't seem to get picked up and I get all warnings, any idea what the issue is?

**Comment by WebFreak001** [comment]
workspace-d uses the dscanner.ini file in your project directory instead of in your home directory.

I could add a config for that

**Comment by gnunn1** [comment]
That's fine, I just didn't realize that. It would be nice if workspace-d checked that no dscanner.ini is in the project directory and if so do not specify it so the global one is used.
