### ISSUE TITLE
vscode.previewhtml not found

### ISSUE THREAD

**Issue by mneilly** [Pure-D/code-d#250]
I'm using vscode 1.33.1 and clicking on the _open project settings_ icon for code-d returns the error `command 'vscode.previewHtml' not found`.

It looks like this is due to Microsoft/vscode#62630 intentionally removing previewHtml in favor of the webview api.

**Comment by WebFreak001** [comment]
oh I thought I changed this API, guess I need to rewrite that now.

Perfect time to add a little bit of styling with the available css variables as I have a bit more experience with it now

**Comment by John-Colvin** [comment]
Any news on this?

**Comment by WebFreak001** [comment]
still need to work on this, the API is a lot different to what I had before (in my debug extension I didn't want to continue with it so I changed it to read only text preview even)

**Comment by HuskyNator** [comment]
I noticed this as well. Out of curiosity, what used to be shown by this button?

**Comment by WebFreak001** [comment]
legacy wiki page: https://github.com/Pure-D/code-d/wiki/Dub-Project-Settings
