### ISSUE TITLE
Server crashed 20 times in the last minute

### ISSUE THREAD

**Issue by zorael** [Pure-D/code-d#252]
Windows 10 x86_64, vscode 1.34.0. code-d is set up to aggressively update and to use the beta stream, and should as such be up to date as of 2019-05-19.

A simple Hello World crashes serve-d until it gives up. I've had it crash in two slightly different ways but this one seems to be more easily reproduced of the two.

```d
module test;

import std.stdio;

void main()
{
    writeln("Hello world!");
}
```

```
2019-05-19T14:11:10.229 [trace] source\served\extension.d:269:syncConfiguration Sending workspace/configuration request for 
2019-05-19T14:11:10.229 [trace] source\served\extension.d:370:doGlobalStartup Initializing serve-d for global access
Server crashed 20 times in the last minute. The server will not be restarted.
[Error - 14:11:10] Connection to server got closed. Server will not be restarted.
```

Attaching example output log. `settings.json` contents seem to be included in the log file.

[code-d crash 2.txt](https://github.com/Pure-D/code-d/files/3195058/code-d.crash.2.txt)

**Comment by WebFreak001** [comment]
hm can you attach to serve-d using a debugger? If you have visual studio installed you can just attach to a running process and then it should stop wherever it is crashing.

You might get better stack traces in it if you compile it yourself with LDC in debug mode:
```
git clone https://github.com/Pure-D/serve-d.git
cd serve-d
dub build --compiler=ldc2
```

**Comment by WebFreak001** [comment]
please try again with code-d 0.21.0 and with that the automatically downloaded newest serve-d version and reopen if it still happens
