### ISSUE TITLE
Add "Open documentation" context menu option for imports

### ISSUE THREAD

**Issue by 0xEAB** [Pure-D/code-d#253]
I'd be nice to have an option to open the dpldocs documentation for imports in the context menu. At least for Phobos + Druntime this  should be doable.

![image](https://user-images.githubusercontent.com/15967408/57983623-7af18180-7a54-11e9-9ee3-79b9d2ba2888.png)

**Comment by WebFreak001** [comment]
you can select it and press ctrl-q ctrl-q

**Comment by 0xEAB** [comment]
well, not bad, but to be honst not really as comfortable as my idea.
