### ISSUE TITLE
Can't seem to build projects with LDC on Mac OS

### ISSUE THREAD

**Issue by AndrejMitrovic** [Pure-D/code-d#254]
I get a build failure with this build task:

```
Error: The dub task detection didn't contribute a task for the following configuration:
{
    "type": "dub",
    "run": false,
    "compiler": "ldc",
    "archType": "x86_64",
    "buildType": "debug",
    "configuration": "application",
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.
```

I've also tried `"compiler": "ldc2"`, same error. I'm not sure how to properly configure it..

**Comment by WebFreak001** [comment]
this is currently a limitation of the build tasks API that all the configuration just gets ignored and I have to provide all possible variations of a configuration in the plugin API. It's implemented as if the API would actually call back to me for "type":"dub" however it never does so unless I explicitly register it with all values

**Comment by AndrejMitrovic** [comment]
I see. It looks like the best thing to do is have a custom task that runs `dub --compiler=ldc2`, which works okay.

**Comment by WebFreak001** [comment]
fixed with next release

**Comment by AndrejMitrovic** [comment]
Thanks a lot for your work @WebFreak001! :)
