### ISSUE TITLE
Cannot create other task than default tasks on wsl

### ISSUE THREAD

**Issue by SjoerdNijboer** [Pure-D/code-d#258]
I've got a task that keeps failing once I try to change the compiler to dmd or the buildtype to release or unittest.

I am using code-d installed with remote development on wsl.

*versions*
WSL=Ubuntu 18.04LTS
D Programming Language (code-d): 0.20.2
DUB: 1.16.0

*Steps to reproduce*
1. setup remote development on wsl.
2. Paste task.json snippet in vscode
3. change debug build to unittests, release, or set the compiler to dmd

*Expected result*
There is now a task that compiles and runs unittest

*Actual result*
The task is not recognised as valid and cannot be started.
The task 'dub: Test swordfish-server` does not compile and run the tests.

*Notes*

task,json
```{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "run my application",
            "type": "dub",
            "run": true,
            "compiler": "ldc2",
            "archType": "x86_64",
            "buildType": "debug",
            "configuration": "application",
            "problemMatcher": []
        },
        {
            "label": "unittest my application",
            "type": "dub",
            "test": true,
            "compiler": "ldc2",
            "archType": "x86_64",
            "buildType": "debug",
            "configuration": "application",
            "problemMatcher": []
        }
    ]
}```

 The following snippet is next to my main method
```
unittest
{
	// Hello unittest world!
	assert(0 == 1);
}
```

Tasks terminal output:
```
Error: The dub task detection didn't contribute a task for the following configuration:
// .... the changed task.
```

`code-d & serve-d` output:
```
2019-07-22T11:34:30.282:app.d:processRequest:77 Calling provideBuildTasks
2019-07-22T11:34:42.497:app.d:processRequest:77 Calling provideBuildTasks
```

With "serve-d.trace.server": "verbose" enabled, I can see more than my two original tasks listed in the output window, but whitout my own task I just edited.

**Comment by WebFreak001** [comment]
see #254

**Comment by SjoerdNijboer** [comment]
Oof! That's quite a limitation.
Seems like this can't be helped then.
Thank you for your quick reaction!
