### ISSUE TITLE
Code completion not working as expected

### ISSUE THREAD

**Issue by dossan** [Pure-D/code-d#26]
So, I am new to D and to code-d. I decide to try your plugin also because I had already tried VSCode and I liked it a lot. I have installed `code-d` as explained here:

> https://github.com/Pure-D/code-d

that is with the following commands:

> cd ~/.vscode/extensions/
git clone https://github.com/WebFreak001/code-d.git
cd code-d
npm install
node ./node_modules/vscode/bin/compile

Now, if I open VSCode and create a `.d` file, first VSCode doesn't recognise the file as a D file (but this could be a VSCode's problem) and then the only thing that I have (after setting the language to D manually) is autocompletion of the foreach look, the main method, etc. Of course I would like to have autocompletion also for all other things, otherwise I would not be trying this plug in. What could eb the problem?

**Comment by WebFreak001** [comment]
Did you install dcd, dfmt, dscanner and workspace-d? Links to all those are in the README

Also if vscode does not recognize it as D file: did you copy the extension to the vscode extensions folder? Alternatively just install it via "ext install code-d" in vscode. Right now there is the latest code-d release

**Comment by dossan** [comment]
Why would you create a wrapper to those 4 if in the installation doesn't not even installs them for you? What's the purpose?

**Comment by WebFreak001** [comment]
I cant bundle native executable in this plugin because its different for every platform. Also just running `dub` in all those packages already compiles them. Its not like in C++ where it takes like 30 minutes for a project
