### ISSUE TITLE
Allocating too much memory

### ISSUE THREAD

**Issue by Beyarz** [Pure-D/code-d#261]
After installing the extension, serve-d started to allocate an impressive amount of memory within minutes. It spawned multiple processes with each allocating more and more memory.

<img width="552" alt="serve-d" src="https://user-images.githubusercontent.com/11684952/62724647-c2642a00-ba13-11e9-962f-ad3a2e2735a1.png">

**Comment by Beyarz** [comment]
The screenshot was taken about one minute after launching vscode

**Comment by WebFreak001** [comment]
did you press save? When saving it compiles the whole project which takes a huge amount of memory

**Comment by Beyarz** [comment]
> did you press save? When saving it compiles the whole project which takes a huge amount of memory

I think that might be the issue, I have auto save on!

**Comment by WebFreak001** [comment]
you can disable the code-d feature using `"d.enableDubLinting": false` which makes it no longer compile on save

**Comment by Beyarz** [comment]
> you can disable the code-d feature using `"d.enableDubLinting": false` which makes it no longer compile on save

This solved it.
