### ISSUE TITLE
segfault loop

### ISSUE THREAD

**Issue by zorael** [Pure-D/code-d#263]
Manjaro/Arch x86_64, vscode 1.37.1, code-d beta stream.

Immediately upon opening vscode, code-d will start to segfault over and over again, until it finally gives up. This was tested with https://github.com/zorael/kameloso, I could not reproduce it with a hello world.

The output log with tracing on: https://www.mediafire.com/file/euj4z65aozw3ud4/code-d.log/file (too large to pastebin)

From the systemd journal;
```
aug 27 14:55:11 xps kernel: serve-d[1485]: segfault at 0 ip 00005578a53bda00 sp 00007fb7ec5f5c30 error 4 in serve-d[5578a4cef000+b1b000]
aug 27 14:55:11 xps kernel: Code: ba 98 0c 00 00 e8 20 c4 f4 ff 55 41 57 41 56 41 55 41 54 53 50 49 89 f6 49 89 ff 31 ed 48 85 ff 74 2f 4c 89 f3 0f 1f 44 00 00 <0f> b6 3b 40 84 ff 78 3
a e8 73 c5 f4 ff 84 c0 74 0d 48 83 c5 01 48
aug 27 14:55:11 xps systemd[1]: Started Process Core Dump (PID 1531/UID 0).
aug 27 14:55:12 xps systemd-coredump[1532]: Process 1485 (serve-d) of user 1000 dumped core.

                                            Stack trace of thread 1485:
                                            #0  0x00005578a53bda00 n/a (/home/zorael/.local/share/code-d/bin/serve-d/serve-d)
```

I went into `~/.local/share/code-d/bin/serve-d` and modified the `release.sh` file to build it in release-debug and not strip the file, but I still only got that systemd coredump backtrace.

**Comment by WebFreak001** [comment]
with code-d 0.21.0 and serve-d 0.5.1 the repo seems to work fine now
