### ISSUE TITLE
failed debugging D-prj at VSCode for Windows

### ISSUE THREAD

**Issue by zelyony** [Pure-D/code-d#266]
I have issue with debugging on Windows:
```
Could not start debugger process, does the program exist in filesystem?
Error: spawn mago-mi ENOENT
```

Windows x64 10 (exactly Server 2019), 
VSCode 1.38.1, 
VisualD installed and I can debug in VStudio
DMD and LDC latest releases (official, not nightly)
packages that installed in VScode:
-    "D Programming Language (code-d)",
-    "D Language utility extension pack"

I have installed VSCodium too (VSCode w/o telemetry): same problem

**Comment by WebFreak001** [comment]
that error message means you don't have mago-mi installed. Either set `magomipath` in your debug configuration to some mago-mi executable or install it to your path.

You can download magomi for example from https://github.com/buggins/dlangide/releases/tag/v0.8.5 or compile it yourself.

Also this is in the wrong repository, code-d doesn't provide debugging support. Please file debug issues to https://github.com/WebFreak001/code-debug
