### ISSUE TITLE
Add an option the display tools versions in an hassle-free manner

### ISSUE THREAD

**Issue by 0xEAB** [Pure-D/code-d#268]
It would be nice to have some feature that allows me to quickly determine which version of…

- DCD
- dfmt
- D-Scanner
- serve-d

…is loaded

**Comment by 0xEAB** [comment]
This would especially help when discovering bugs in those utils. So one would know which version one's on, and whether a simple update might help.

**Comment by WebFreak001** [comment]
I can tell the workspace-d & serve-d version but for the beta stream not the dependencies. However I can add a note that "dub, dscanner and dfmt are bundled" and change that note on release commits to the dub.json versions

**Comment by 0xEAB** [comment]
Maybe one should consider adding such a feature to the D-Scanner and dfmt libraries. Because both already determine their version number on pre-generate.

**Comment by 0xEAB** [comment]
> dub, dscanner and dfmt

DCD should probably the easiest one. Because the feature is basically already there (-> update checks)

**Comment by WebFreak001** [comment]
DCD is also the one which is already logged
