### ISSUE TITLE
Connection to the server got Closed / serve-d crash

### ISSUE THREAD

**Issue by mario-tripaneer** [Pure-D/code-d#269]
Greetings, I'm not able to get the extension to work, the output logs a series of messages : 
```[Info  - 5:41:01 PM] Connection to server got closed. Server will restart.```

Already tried removing all user settings, doing a clean re-install (followed by "Compile from source" prompt) but the out put remains the same. Using macOS 10.15 and dmd v2.088.0.

trying to build and running serve-d manually results in ```Abort trap: 6```

```~/.vscode/extensions/webfreak.code-d-0.20.2/bin/serve-d
$ dub build --force && ./serve-d --version
Running pre-generate commands for dfmt...
Running pre-generate commands for dscanner...
Performing "debug" build using /Library/D/dmd/bin/dmd for x86_64.
diet-complete 0.0.3: building configuration "library"...
stdx-allocator 2.77.5: building configuration "library"...
emsi_containers 0.8.0-alpha.15: building configuration "library"...
eventsystem 1.2.0: building configuration "library"...
libdparse 0.11.6: building configuration "library"...
libddoc 0.6.1: building configuration "lib"...
dunit 1.0.15: building configuration "library"...
painlesstraits 0.3.0: building configuration "unittest"...
painlessjson 1.4.0: building configuration "library"...
cachetools 0.3.1: building configuration "library"...
requests 1.0.9: building configuration "std"...
serve-d:http 0.4.1+commit.55.g06d6a33: building configuration "library"...
dfmt 0.10.1: building configuration "library"...
dsymbol 0.6.4: building configuration "library"...
../../../../../.dub/packages/dsymbol-0.6.4/dsymbol/src/dsymbol/symbol.d(204,10): Deprecation: Cannot use alias this to partially initialize variable part of type SymbolOwnership. Use part.ptr
inifiled 1.3.1: building configuration "library-quiet"...
dscanner 0.7.2: building configuration "library"...
dub 1.16.0: building configuration "library"...
Serializing composite type BuildRequirements which has no serializable fields
Serializing composite type BuildOptions which has no serializable fields
isfreedesktop 0.1.1: building configuration "library"...
xdgpaths 0.2.5: building configuration "library"...
standardpaths 0.8.1: building configuration "default"...
workspace-d 3.4.0-pre11: building configuration "library"...
serve-d 0.4.1+commit.55.g06d6a33: building configuration "application"...
Linking...
Abort trap: 6
```

**Comment by 0xEAB** [comment]
> `Abort trap: 6`

Does this come from your linker or from serve-d?

**Comment by mario-tripaneer** [comment]
This is from the execution of serve-d
```$ ./serve-d --version
Abort trap: 6```

**Comment by WebFreak001** [comment]
did you change your linker or something? Try compiling and running a hello world D program

**Comment by mario-tripaneer** [comment]
This issue came as I've updated the macOS version to 10.15 last week, which in turn required the dmd version to be updated as well to v2.088.0.
Compilation and execution is working without issues for other programs and the apps I'm working on. So far only saw this happening with serve-d.

**Comment by WebFreak001** [comment]
can you try `dub build --compiler=ldc2` for manually compiling?

**Comment by mario-tripaneer** [comment]
Also got the same result with that compiler.

But managed to narrow down where the error is coming from and seems like its the requests library, which is being imported in your http lib. 
Commenting out the ```import requests;``` and the code that uses it prevented the immediate crash at launch (just importing the lib is enough to cause it)

**Comment by mario-tripaneer** [comment]
Yes, that binary seems to be working fine, thank you

**Comment by WebFreak001** [comment]
there might be an issue with your setup or with dmd. That binary is compiled with LDC, can you maybe try using LDC? Though the tests on the CI on OSX with DMD also pass so I don't really think that would be an issue.

**Comment by mario-tripaneer** [comment]
I got to the bottom of it, the issue as to do with the openssl changes in macOS 10.15 Catalina. I fixed it by updating the libssl.dylib and libcrypto.dylib libraries manually (which the dlang-requests package is using)

For reference , here's the a discussion about that issue if anyone else runs into this : https://forums.developer.apple.com/thread/119429

**Comment by WebFreak001** [comment]
ah I see. Yes openssl changes like to break things very quickly. Still that doesn't really explain why it works with the precompiled binary from the CI I think. Why would it crash only when compiling on a newer mac version, even though the issue happens when running on a newer system with newer dylibs, thus only changing when running and also when the dylibs change?

**Comment by mario-tripaneer** [comment]
Indeed, very strange how the precompiled worked before updating the libs.. i wonder where's the difference when compiling on the newer system that made older libs incompatible

**Comment by WebFreak001** [comment]
there are precompiled binaries always downloaded now with 0.21.0 so this shouldn't happen anymore
