### ISSUE TITLE
Client and Server mismatch

### ISSUE THREAD

**Issue by viveksachidananda** [Pure-D/code-d#273]
client & server version mismatch

I upgraded the MAC Os to latest version and DMD to 288.0 and after which Visual studio - Code-d is not working.

I manually installed again now I get a new issue saying the client and server do not match.

![Screenshot 2019-11-05 at 09 14 55](https://user-images.githubusercontent.com/10163902/68190006-ddabea80-ffac-11e9-83a8-3afe3ddbd627.png)

**Comment by WebFreak001** [comment]
what do the DCD client and server executables, which are configured in your user settings or otherwise system wide installed, say when you call both with `--version`?

**Comment by viveksachidananda** [comment]
Thanks! 
I checked and DCD was not working! After checking with DCD space found that issue is known for Catalina release and got fixed by compiling the DCD release manually!
