### ISSUE TITLE
can not autocomplete

### ISSUE THREAD

**Issue by LanceAdd** [Pure-D/code-d#274]
when i reinstall the plugin in vscode, it can't autocomplete the code; what settings i need to change in vscode to get the autocomplete function

**Comment by WebFreak001** [comment]
can you post the logs or behavior on startup? I believe the issue creation screen should have instructed you to do this so you can read in there how to do it again.

alternatively try the current release candidate: https://wfr.moe/f6tywt/code-d-0.21.0.vsix

**Comment by LanceAdd** [comment]
it can't automatically prompt or supplement my import package.

**Comment by LanceAdd** [comment]
do i neet to install workspace-d like this?
![image](https://user-images.githubusercontent.com/22969676/68745110-fbbebe00-0630-11ea-8413-b6711716c477.png)

**Comment by WebFreak001** [comment]
no, that has been removed and outdated for 2 years now.

can you send a screenshot of what's broken?

**Comment by LanceAdd** [comment]
thank you for you help, I have slove the problem，i reinstall the dmd frome Official website and remove the dmd installed by brew, then it work correct. I think this is was some directories issue.thanks

**Comment by WebFreak001** [comment]
in this case it just didn't find the standard libraries for auto completion. Though with the release candidate link I sent it should have still worked now.

Well if you want to go back, you can manually set `"d.stdlibPath"` to the phobos and druntime import folders to fix it or leave it like this and have it automatically discover the standard libraries.
