### ISSUE TITLE
vibe.d projects lack linting

### ISSUE THREAD

**Issue by 98982872** [Pure-D/code-d#276]
In the recent release, code-d offers more static linting support for regular dub projects. But vibe.d projects don't seem to provide new linting.

**Comment by WebFreak001** [comment]
can't reproduce on a freshly created project:

![](https://wfr.moe/f6tsEg.png)

is vibe.d perhaps missing the version number in the dub dependencies view?

![](https://wfr.moe/f6tBx1.png)

in this case just run your app once and then press the reload button in that view and everything will work again.

**Comment by 98982872** [comment]
>in this case just run your app once and then press the reload button in that view and everything will work again.

Okay that seemed to fix it. Closing.
