### ISSUE TITLE
Running "dub-auto: Run" and "dub-auto: Build" complains about the command being unrecognized

### ISSUE THREAD

**Issue by andrejp88** [Pure-D/code-d#277]
When either of these two are run, the following is visible in the terminal:

```
> Executing task: """dub" "build" "--compiler=dmd" "-a=x86_64" "-b=debug" "-c=application""" <

'""dub" "build" "--compiler' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

I think those extra quotations are causing problems. When I run that command manually, as well as when I run just `"""dub"` without any arguments, it says:

```
Unknown command: dub

USAGE: dub [--version] [<command>] [<options...>] [-- [<application arguments...>]]

Manages the DUB project in the current directory. [...etc. etc.]
```

Somehow, typing `"""dub"` simultaneously both is and isn't recognized as a program.

Thanks. I accidentally submitted this issue before I finished writing it, sorry if that caused some confusion.

On a side note - is it possible to assign "dub-auto: Run" to a specific keyboard shortcut or button on the status bar? I've found ways to create buttons that run specific commands, but then it doesn't use the configuration/arch/etc. that can be set in the status bar.

**Comment by WebFreak001** [comment]
hm not sure how the `"""dub"` issue happens, it's probably an issue with quoting because vscode forced me to use the shell execution task instead of the process execution task because otherwise on linux it errored out that dub is not a valid shell process to launch or something like that. I could add a platform check here I think.

I can add "auto" to the arch, compiler, etc flags to fetch the from the status bar

**Comment by andrejp88** [comment]
I should have mentioned - I'm using Windows and vscode's terminal uses the native command prompt.

I just tried switching the default shell in vscode to bash, and now the run command works fine. It might be important that now it prints this:

```
> Executing task: 'dub' 'run' '--compiler=dmd' '-a=x86_64' '-b=debug' '-c=application' <
```

...without the redundant quotation marks. So I guess it's a windows-specific bug?

I'm not sure what you mean by adding "auto" to fetch from the status bar, from what I can tell, it already does that? Or do you mean it's possible to set "auto" as the value for the `--arch`/`--compiler`/etc flags?

**Comment by WebFreak001** [comment]
yes I meant when changing it to "auto" in a custom defined task because it's currently not possible to have it automatically take these values outside of `dub-auto: ...` tasks

**Comment by andrejp88** [comment]
Ah I see. Thank you for your amazing work on this plugin!
