### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by yannick** [Pure-D/code-d#28]
from about here:
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/utils/dictionarylist.d#L129
code highlighting starts to fail.

**Comment by WebFreak001** [comment]
Uses the same syntax highlighting as atomize-d right now. Will be fixed after this: https://github.com/Pure-D/atomize-d/issues/31

**Comment by Vild** [comment]
b925ec2  fixed this
