### ISSUE TITLE
Add "Run Test Task" to global menu "Terminal"

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#281]
Does you have the possibility to add a menu item `Run Test Task` (With keyboard shortcut, maybe Shift + F10) side by side to `Run Build Task` in global menu `Terminal`?

**Comment by WebFreak001** [comment]
test integration is planned in #279

for the build tasks it should be possible to bind them to keyboard shortcuts and with that also run dub test (refer to vscode documentation for this)

**Comment by WebFreak001** [comment]
the Run Test Task command can simply be bound in the keyboard shortcuts settings. (the ID is `workbench.action.tasks.test` if you use the JSON editor)

to put it in the "Terminal" menu please open an issue at Microsoft/vscode
