### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pantojaja** [Pure-D/code-d#284]
- Issue Type: `Performance`
- Extension Name: `code-d`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.42.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\DELL1\webfreak.code-d-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by WebFreak001** [comment]
what were you doing when you were experiencing high CPU load? Could you also please attach your cpuprofile file?
