### ISSUE TITLE
Navigation to DScanner issue file locations

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#289]
![image](https://user-images.githubusercontent.com/1451047/74931000-0bdbfb80-53df-11ea-94e2-27568949216d.png)

For DSCanner issues I can click on the link but this only opens the file in the editor but not jumps to the actual line of the issue.

While hovering over the line, only the file part is underlined as link but not the line number suffix `(31:19)`. For DMD syntax errors both, the file and the line number text is underlined and forward navigation to the actual line is possible.

**Comment by WebFreak001** [comment]
uh is this in the command line? That's a vscode core thing to show the links

**Comment by andre2007** [comment]
Yes, it is in the terminal view of VSC. I now also saw the difference. DScanner is using `:` between line and column number while DMD is using a `,`.

(31:19) vs (31,19)
I wonder whether we should change this in DScanner or should I create an enhancement request for VSC?

**Comment by WebFreak001** [comment]
could the integrated D-Scanner in serve-d be improved to do what you are looking for?

**Comment by andre2007** [comment]
I using only the serve-d integrated D-Scanner but just noticed by chance the mentioned behavior. As it is not related to this plugin I will close this issue.
