### ISSUE TITLE
Very minimal linting on library type projects

### ISSUE THREAD

**Issue by 98982872** [Pure-D/code-d#291]
In projects where app.d and main() is not present, linting support is very minimal.

- Doesn't check for non-existent module imports

- Doesn't check syntax 

- Doesn't check any other errors apart from not documenting public symbols and possible missed opportunity to declare a symbol as const/immutable

Running on the latest version along with the latest dmd on snap.

**Comment by andrejp88** [comment]
I am working on a library and I'm pretty sure all linting rules are being obeyed (definitely the ones you mentioned at least). What happens if you run `dub lint` or `dscanner` manually?

**Comment by 98982872** [comment]
> I am working on a library and I'm pretty sure all linting rules are being obeyed (definitely the ones you mentioned at least). What happens if you run `dub lint` or `dscanner` manually?

Actually, everything started working once I issued `dub build` once. Closing.
