### ISSUE TITLE
New dfmt option: disabling automatic line breaks

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#293]
Dfmt provides a new option [Support disabling automatic line breaks](https://github.com/dlang-community/dfmt/pull/471).

Could you add a new option to switch on / off this feature in code-d Settings?

**Comment by WebFreak001** [comment]
planning on defaulting that feature in code-d and making a switch to turn it back again

**Comment by buckle2000** [comment]
Is it possible to automatically detect available options from `dfmt -h`? It may save time the next time dfmt has new options.

Also, I'd like to manually specify options to `dfmt`.

**Comment by Temtaime** [comment]
@WebFreak001 is there a way adding custom dfmt command line switches for now ?

**Comment by WebFreak001** [comment]
sorry that's not possible because serve-d bundles its own dfmt version, so even if you could pass your own argument strings, the dfmt command line parser I'm calling wouldn't recognize them.

**Comment by Soaku** [comment]
@WebFreak001 couldn't there be an option to just call `dfmt -i` on formatter requests, effectively using editorconfig?

**Comment by WebFreak001** [comment]
I used dfmt as external application before, especially on windows it's quite bad with the performance. I guess having it as opt-in option it would work but idk if that's really worth being in scope of code-d/serve-d when you could basically install a separate extension if you want raw dfmt directly called.

**Comment by WebFreak001** [comment]
keep_line_breaks has been default since last release
