### ISSUE TITLE
Coverage not working: d related coding is in sub folder

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#294]
I open a folder as root folder in VSC with following structure

```
- d
    .dub
    dub.json
    source
    source-*.lst
- .gitignore
- dockerfile
```

Coverage related functionality (percentage, coloring) is not working. It only works if I open folder `d` as root folder in VSC.

**Comment by deviator** [comment]
similar problem if use [dstpath](https://dlang.org/articles/code_coverage.html#switchdstpath) DRT option

please add configuration for coverage directory
