### ISSUE TITLE
Dub lint: build type syntax

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#298]
Dub build has since some months a built type `syntax`. Therefore no binaries are created for linting a project using `dub build`.

**Comment by WebFreak001** [comment]
uhh what's your requested change/suggestion?

**Comment by andre2007** [comment]
At the moment binaries are created for testing the syntax using dub. This is unnecessary and makes the syntax check slow. By calling dub build with build type syntax the syntax check will become much faster as no binaries will be written to harddisk.

**Comment by WebFreak001** [comment]
what serve-d version are you using? This has long been fixed

**Comment by andre2007** [comment]
I am using recent version but tried to validate it by reading the source code. I didn't saw that build type syntax is used. But if this is already done, that's great.

**Comment by WebFreak001** [comment]
here is the source code which does it: https://github.com/Pure-D/workspace-d/blob/b969f3fe820dc6b4099ff5c5ce10ab210334ec93/source/workspaced/dub/lintgenerator.d#L37 (custom generator)
