### ISSUE TITLE
workspace-d and dcd-server should stop when closing vscode

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#3]
With this plugin workspace-d and dcd-server start automatically when working with D files, however if you close vscode these processes remain behind. They should be closed when vscode closes IMHO. If I re-start vscode I get new workspace-d and dcd-server processes.

**Comment by WebFreak001** [comment]
Thats a problem with vscode because I already added it to the dispose function but they never get called even though i register them. See https://github.com/WebFreak001/code-d/blob/master/src/extension.ts#L19 and https://github.com/WebFreak001/code-d/blob/master/src/workspace-d.ts#L196-L202

**Comment by gnunn1** [comment]
I think this has been fixed in vscode 0.10.5 as workspace-d is no longer running after I exit vscode, can you confirm?

**Comment by WebFreak001** [comment]
Confirmed fixed in vscode 0.10.6
