### ISSUE TITLE
turn off undocumented/const checks by default

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/code-d#304]
probably not a good user experience to get the undocumented/const checks by default

unused is shown as grayed out right now already

**Comment by dgellow** [comment]
Do you mean this warning? If you do, yes please, that's a really noisy one!

![image](https://user-images.githubusercontent.com/2451004/80523689-bf88db00-898e-11ea-9a86-c1c7d98bb72f.png)

**Comment by WebFreak001** [comment]
both disabled since latest serve-d + code-d release
