### ISSUE TITLE
Ability to turn off module name insertion

### ISSUE THREAD

**Issue by buckle2000** [Pure-D/code-d#306]
Is it possible to turn off module name insertion on new files? The extension always generate the module name even if it is illegal. I'd like to turn it off for non-dub projects.

I have no idea how that got added to a new file. The message is not even in the source code.

**Comment by WebFreak001** [comment]
there is `"d.generateModuleNames": true` now, if you use serve-d nightly it will be available to you in a few hours.

VSCode will gray it out because it doesn't know about it yet but it will still be sent so it will still disable if you turn it to false.
