### ISSUE TITLE
Track compatible versions of DCD, etc

### ISSUE THREAD

**Issue by earthfront** [Pure-D/code-d#31]
Installation requires existing accessible binaries for DCD, dfmt, etc:
https://github.com/Pure-D/code-d#installation

In my setup (Ubuntu x64), they are installed, and vscode auto-completion worked for a period. 
Then I updated them to the latest (cd dcd; git pull; make; cp bin/dcd* ~/bin). 
Now code-d auto-completion doesn't work. vscode shows errors such as: "Failed to kill DCD-Server. See console for details." when attempting to restart DCD.

I assume this is because I updated my version of DCD to the latest. 
Reverting the version might fix this, but there's no way to know what version was used previously (or which one code-d was tested with). My DCD repo was tracking the HEAD on master.

Possible solutions:
- Check and require versions of DCD, dfmt, etc. at runtime. 
- Maintain git submodules pointing to the correct versions of DCD. Build all with code-d/workspace-d.

**Comment by earthfront** [comment]
Which versions of DCD, dfmt, Dscanner, and workspace-d were used to test code-d?

**Comment by WebFreak001** [comment]
try downgrading DCD to some version which doesnt use Unix Domain Sockets (the latest non pre-release)

**Comment by earthfront** [comment]
Downgraded to v0.7.5; works.

Version mismatch will be a problem in the future. Any interest in pursuing the solutions I mentioned?

**Comment by WebFreak001** [comment]
https://github.com/Hackerpilot/DCD/issues/295

Should be fixed by checking version >= 0.8.x first

**Comment by WebFreak001** [comment]
Fixed in workspace-d: https://github.com/Pure-D/workspace-d/commit/6f061b8942bf4645798e44e43abb883fd77097ba

**Comment by WebFreak001** [comment]
note: might not work quite as expected because of https://github.com/Hackerpilot/DCD/issues/297

**Comment by earthfront** [comment]
Thanks! You're the man!
