### ISSUE TITLE
Disable "A request has failed" notification

### ISSUE THREAD

**Issue by danbarbarito** [Pure-D/code-d#310]
Whenever I type something that contains a syntax error (for example: `if 123 { `) I get a message that looks like this:

<img width="1031" alt="Screen Shot 2020-05-10 at 11 30 18 AM" src="https://user-images.githubusercontent.com/5640055/81503471-c0d0d680-92b1-11ea-8e76-cea7c362d022.png">

This is **really** annoying and I can't find a way to disable this notification. Any ideas on how to disable this?

----

Running on macOS High Sierra

Using the the current latest version of code-d (fd084417b13e6189686727dcfc81e58fa04f5d3f)

dcd version v0.11.1

serve-d v0.1.3 with workspace-d v2.12.0

**Comment by WebFreak001** [comment]
serve-d 0.1.3? You sure that's right?

**Comment by danbarbarito** [comment]
@WebFreak001 that is what the output of --version is
```bash
serve-d --version
  serve-d v0.1.3 with workspace-d v2.12.0
  Included features: "d"
```

**Comment by danbarbarito** [comment]
@WebFreak001 Actually you're right, i was looking at the wrong serve-d I guess. Using this:

serve-d v0.6.0 with workspace-d v3.5.0
Included features: "d", "workspaces"
Built: Mon Dec 16 17:16:17 2019
with compiler LDC v2.88 on osx littleEndian
dub, dfmt and dscanner are bundled within (compiled in)

**Comment by Geod24** [comment]
Just hit the same issue. Installed code-d on my friend laptop and teaching her programming. Whenever she saves after forgetting a semicolon, this message pops up and switch window (she usually uses the terminal to compile).

**Comment by WebFreak001** [comment]
uh this sounds like something which should really not happen

can you try setting the Served Release Channel to nightly to see if the issue persists? (`"d.servedReleaseChannel": "nightly"`)

**Comment by Geod24** [comment]
That did fix it, thanks!

**Comment by danbarbarito** [comment]
This fixed it for me as well, thank you!
