### ISSUE TITLE
Running a project without dub (single file / rdmd style)

### ISSUE THREAD

**Issue by Geod24** [Pure-D/code-d#311]
Hey,
Not *too* familiar with VSCode myself, but a bunch of friends / coworkers use it and I sometimes run into issues.
One thing that showed up recently is the straightforward ability to run a file. I'm teaching a friend to code and we opened an empty folder, created a single `main.d` and started to code. When came the time to run it, `run` asked me to select a configuration, either Node.js or made my own.

I'm aware that it's simple enough to add a configuration with VSCode, but I was wondering if there was / could be any support for this directly into the extension ?

**Comment by WebFreak001** [comment]
rightclick the file, choose "run with rdmd"

**Comment by Geod24** [comment]
Thanks! Good to know. I guess it's not worth having the ability to do it via the `run` shortcut then.

**Comment by WebFreak001** [comment]
if you have an example of other extensions (like the nodejs extension) doing it in another way, feel free to comment it here as feature request
