### ISSUE TITLE
Could not initialize DCD for /Users/a/sauv/htdocs/MES-SITES/info/site. client & server version mismatch

### ISSUE THREAD

**Issue by fredOnGitHub** [Pure-D/code-d#312]
OS : MAC 10.15.4 
VSCODE : Version: 1.45.1

Hello, i have installed code-d but I have this message
```
Could not initialize DCD for /Users/a/sauv/htdocs/MES-SITES/info/site. client & server version mismatch
```

With 

- brew install dcd
- brew install dub
- ext install webfreak.code-d

or directly 
- ext install webfreak.code-d

OK i get
![Capture d’écran 2020-05-17 à 11 28 02](https://user-images.githubusercontent.com/9338756/82140966-f38b4980-9832-11ea-9e75-15340eb5f92f.png)

but It is the same I get:
![Capture d’écran 2020-05-17 à 11 28 33](https://user-images.githubusercontent.com/9338756/82141001-3816e500-9833-11ea-81c3-3ae138a42b14.png)

Thanks for your help

**Comment by WebFreak001** [comment]
what do your user settings say for d.dcdClientPath and d.dcdServerPath?

**Comment by fredOnGitHub** [comment]
> what do your user settings say for d.dcdClientPath and d.dcdServerPath?
![Capture d’écran 2020-05-17 à 12 35 31](https://user-images.githubusercontent.com/9338756/82142230-16216080-983b-11ea-8922-bf6ec775efda.png)
and
![Capture d’écran 2020-05-17 à 12 35 47](https://user-images.githubusercontent.com/9338756/82142236-1de10500-983b-11ea-8bf6-f27ba4eba04e.png)

**Comment by WebFreak001** [comment]
it seems you already had DCD versions installed globally, which it auto detected and reused. Can you check if your global dcd-client and dcd-server executables are of the same version?

**Comment by fredOnGitHub** [comment]
![Capture d’écran 2020-05-17 à 12 50 47](https://user-images.githubusercontent.com/9338756/82142507-191d5080-983d-11ea-996b-d049e29d64f1.png)
![Capture d’écran 2020-05-17 à 12 51 03](https://user-images.githubusercontent.com/9338756/82142508-1d496e00-983d-11ea-8ebb-e02be20c3e9e.png)

**Comment by fredOnGitHub** [comment]
> it seems you already had DCD versions installed globally, which it auto detected and reused. Can you check if your global dcd-client and dcd-server executables are of the same version?

![Capture d’écran 2020-05-17 à 12 50 47](https://user-images.githubusercontent.com/9338756/82142517-2afef380-983d-11ea-8a38-e3eb81e93ecb.png)

![Capture d’écran 2020-05-17 à 12 51 03](https://user-images.githubusercontent.com/9338756/82142522-39e5a600-983d-11ea-826f-26cf30fb8ba4.png)

**Comment by WebFreak001** [comment]
ah sorry this has been a long standing issue which has already been fixed but will be available on next release only. To work around this, check #286

**Comment by fredOnGitHub** [comment]
> ah sorry this has been a long standing issue which has already been fixed but will be available on next release only. To work around this, check #286

From #286 I get
![Capture d’écran 2020-05-17 à 13 06 46](https://user-images.githubusercontent.com/9338756/82142820-76b29c80-983f-11ea-8760-992ce9d7dc11.png)

**Comment by WebFreak001** [comment]
oh I see in this case serve-d is preferring the local installed DCD over the global installed DCD. You could either try to delete the dcd-server/dcd-client in your code-d/bin folder (unstable) or change your user settings dcd client/server path to the global paths (`/usr/local/bin/dcd-*`)

**Comment by fredOnGitHub** [comment]
> oh I see in this case serve-d is preferring the local installed DCD over the global installed DCD. You could either try to delete the dcd-server/dcd-client in your code-d/bin folder (unstable) or change your user settings dcd client/server path to the global paths (`/usr/local/bin/dcd-*`)

From the first option
I have deleted the dcd-server/dcd-client in my code-d/bin folder 
![Capture d’écran 2020-05-17 à 13 26 22](https://user-images.githubusercontent.com/9338756/82143182-37d21600-9842-11ea-954d-aa3635bab70e.png)

Rebooted VSCode

But there is a reinstallation of the package
![Capture d’écran 2020-05-17 à 13 25 31](https://user-images.githubusercontent.com/9338756/82143196-5cc68900-9842-11ea-9e96-58d286fe916d.png)

And after I see again
![Capture d’écran 2020-05-17 à 13 29 16](https://user-images.githubusercontent.com/9338756/82143221-85e71980-9842-11ea-89cc-5d1d3992cb26.png)

**Comment by fredOnGitHub** [comment]
> > oh I see in this case serve-d is preferring the local installed DCD over the global installed DCD. You could either try to delete the dcd-server/dcd-client in your code-d/bin folder (unstable) or change your user settings dcd client/server path to the global paths (`/usr/local/bin/dcd-*`)
> 
> From the first option
> I have deleted the dcd-server/dcd-client in my code-d/bin folder
> ![Capture d’écran 2020-05-17 à 13 26 22](https://user-images.githubusercontent.com/9338756/82143182-37d21600-9842-11ea-954d-aa3635bab70e.png)
> 
> Rebooted VSCode
> 
> But there is a reinstallation of the package
> ![Capture d’écran 2020-05-17 à 13 25 31](https://user-images.githubusercontent.com/9338756/82143196-5cc68900-9842-11ea-9e96-58d286fe916d.png)
> 
> And after I see again
> ![Capture d’écran 2020-05-17 à 13 29 16](https://user-images.githubusercontent.com/9338756/82143221-85e71980-9842-11ea-89cc-5d1d3992cb26.png)

With the second option I get
![Capture d’écran 2020-05-17 à 13 37 26](https://user-images.githubusercontent.com/9338756/82143363-93e96a00-9843-11ea-8475-d60e708656c2.png)

**Comment by Geod24** [comment]
@fredOnGitHub : Are you using dcd for anything else than VSCode ? You also need to also `brew remove dcd`.

**Comment by fredOnGitHub** [comment]
> @fredOnGitHub : Are you using dcd for anything else than VSCode ? You also need to also `brew remove dcd`.

Hello, 

It was tested like that before.
I am using dcd only with VSCode.


This Saturday, June 6, 2020.
No dcd or dub installed 

`brew list`

 ![Capture d’écran 2020-06-06 à 12 53 32](https://user-images.githubusercontent.com/9338756/83942555-be03cb80-a7f4-11ea-950b-5ff50dc4ea3c.png)

```
$ which dcd-client
dcd-client not found

$ which dcd-server
dcd-server not found

$ ls ~/.code-d*
zsh: no matches found: /Users/fredericcarpon/.code-d*
```

Installation of the plug-in

`ext install webfreak.code-d`

I have , this This Saturday, June 6, 2020, the same issue



![Capture d’écran 2020-06-06 à 12 48 49](https://user-images.githubusercontent.com/9338756/83942632-9e20d780-a7f5-11ea-96f8-486077bba24f.png)

![Capture d’écran 2020-06-06 à 12 49 05](https://user-images.githubusercontent.com/9338756/83942633-aa0c9980-a7f5-11ea-85b6-6cee1091f179.png)

![Capture d’écran 2020-06-06 à 12 49 21](https://user-images.githubusercontent.com/9338756/83942744-b7765380-a7f6-11ea-80ad-bc5565001953.png)

**Comment by sstadick** [comment]
I have the same issue. I have dmd and dub installed via brew. No global dcd*. I install the extension, it installs dcd* in the ~/.code-d/bin and then the "Could not initialize DCD for <me>..." message comes up. I'm on mac.

**Comment by WebFreak001** [comment]
this is very likely an issue with the precompiled DCD binaries. The latest workspace-d will fix this with including dcd-client as library and more compatibility versions with dcd-server, however for this first DCD needs a new release tagged and release on dub.

There are newer working precompiled DCD binaries starting with v0.12.0, however that version has a severe flaw in symbol resolution making auto completion much worse so I downgraded the downloaded DCD version currently. This was an issue in dsymbol which is fixed in master, however upgrading this will also require the newest libdparse release to be available on dub.

Currently on dub libdparse doesn't upgrade so the programs are kind of stuck not upgradable. Once it does release however we can also publish new dsymbol and dcd and new dfmt and dscanner. The current workspace-d changes are dependent on current DCD changes to compile properly, so until there is a new DCD release (which in turn needs a new dsymbol release which should contain the latest libdparse release) this is kind of stuck.

As a workaround it's possible to clone DCD yourself, `git checkout v0.11.0` and build `dub build --config=client` and `dub build --config=server` and configure these generated ./bin/dcd-client and ./bin/dcd-server binaries in your user settings (and reload) to have something working.

**Comment by TheSpydog** [comment]
I noticed that DCD 0.13.0 released last week. Do you have an estimate for when the new version of code-d will be released to the VS Code marketplace? For some reason the workaround above didn't work for me.

**Comment by WebFreak001** [comment]
There is still a small protection bug making auto completion miss a few symbols which are currently working fine, so I wait for that to be fixed first before making everyone upgrade to it. However you can already use it if you set `d.servedReleaseChannel` to `nightly` in your user settings right now and reload.

**Comment by WebFreak001** [comment]
assuming fixed with last release
