### ISSUE TITLE
Non dub project, can't get DCD to recognize importPaths

### ISSUE THREAD

**Issue by stereokai** [Pure-D/code-d#313]
According to [Configuring non-DUB projects](https://github.com/Pure-D/code-d/blob/master/docs/non-dub.md), I configured my user settings as so:
```json
    "d.projectImportPaths": [
        "dependency1",
        "dependency2",
        "dependency3",
    ],
    "d.neverUseDub": true,
```

But none of my imports are recognized by code-d.

Without the settings above, I am getting `Could not resolve location of module` for all of my local imports.

The project is a source library and not a program that is built. what am I doing wrong?

**Comment by WebFreak001** [comment]
what is your dependency folder structure? If you have a dependency1/source/mypkg/foo.d then you need to specify `dependency1/source` as import path (assuming for foo.d the module is `module mypkg.foo`)

**Comment by stereokai** [comment]
Thanks for such a quick answer!

Ok so let's say my folder structure is like this:

```
project root
+--- some-file.d
+--- component
     +--- subcomponent
          +--- common.d
```

In `some-file.d`, there's an `import` for:
```D
import projectname.component.subcomponent.common;
```
and `projectname` is defined in `dub.sdl`

**Comment by WebFreak001** [comment]
hm it doesn't sound like it would work like that. DCD assumes that module names are exact mappings of the filesystem, so in pseudo code this is what it does to lookup your import:

```d
foreach (importPath; importPaths)
    if (fileExists(importPath ~ importName.replace('.', '/') ~ ".d"))
        return useThisFile;
```

So in your example at least a folder named "projectname" must exist containing "component" in order for you to be able to import your `some-file.d` there. Additionally `some-file.d` wouldn't be a valid name for it, it either needs to be `common.d` or `package.d` inside a `common` directory for your module name there.

When doing that you can use `sourcePaths "."` and `importPaths "."` [like in vibe.d](https://github.com/vibe-d/vibe.d/blob/ecbdc5d19b55619a75e087e0979e9540311ebbe6/mongodb/dub.sdl)

**Comment by stereokai** [comment]
Sorry, I'm new to D and just starting out today. The file name is `common.d` in fact, I just thought I'll give it some generic name to prevent confusion.

But in fact, I just realized the file tree I posted above is incorrect and confusing. Here is an accurate one:
```
project root
+--- some-file.d
+--- component
     +--- subcomponentA
          +--- subcomponentB
               +--- subcomponentC
                    +--- common.d (imported)
     +--- subcomponentD
          +--- subcomponentE
               +--- common.d (importing)
```
And the `import` directive is:
```D
import projectname.subcomponentA.subcomponentB.subcomponentC.common;
```

How about now?

**Comment by WebFreak001** [comment]
> So in your example at least a folder named "projectname" must exist containing "component" in order for you to be able to import your some-file.d there

still missing a folder called `projectname`

**Comment by WebFreak001** [comment]
or well to fix your example:
```
project root
+--- some-file.d
+--- component
     +--- projectname
          +--- subcomponentA
               +--- subcomponentB
                    +--- subcomponentC
                         +--- common.d (imported)
+--- anotherComponent
     +--- projectname
          +--- subcomponentD
               +--- subcomponentE
                    +--- common.d (importing)
```

and your import paths would be `component` and `anotherComponent` in this example. Then you can import
```d
import projectname.subcomponentA.subcomponentB.subcomponentC.common;
```

Otherwise you will need to change the module definition of your source files to not start with "projectname." if you want it to work with DCD.

**Comment by stereokai** [comment]
Thanks so much for elaborating. It's not my project so I'll bring it up with the owner, and report back.

**Comment by stereokai** [comment]
@WebFreak001 mystery solved lol. In this project that I joined, the project root is one level above the dub.sdl file (it's one level above the git repo root). Is there any way to configure code-d to resolve `importPaths` one level above the dub file?

**Comment by WebFreak001** [comment]
no, this is a DCD limitation

but maybe it would be possible to work around trivial cases like this with symlinks in /tmp on unix systems

**Comment by stereokai** [comment]
> but maybe it would be possible to work around trivial cases like this with symlinks in /tmp on unix systems

How would that be done?

> no, this is a DCD limitation

Well in this project they're using Emacs which makes that possible somehow, but I don't have Emacs and I'm on Windows

**Comment by stereokai** [comment]
@WebFreak001 any chance I can hear from you on this before the weekend? :)

**Comment by WebFreak001** [comment]
for your project if "project root" is the name of the root package, it would work with .. as import paths.

But I wouldn't recommend that because you would pollute your imports with all other folders in the parent directory. However this is how I could imagine they got theirs to work.

I haven't done any work on doing changes on this yet.

**Comment by stereokai** [comment]
Thanks for getting back.

Your comment helped. I finally sorted it out.
```
projectName
+--- projectName // root folder opened in VSCode. This is also the main component. All modules in the folder are defined under projectName namespace
     +--- component1
          +--- subcomponent1
               +--- common.d (importing)
     +--- component2
          +--- subcomponent2
               +--- common.d (imported)
+--- dependency
     +--- component3
          +--- subcomponent3
               +--- common.d (imported)
```

The importing `common.d` imports both `projectName.component2.subcomponent2.common.d` and `dependency.component3.subcomponent3.common.d`.

My code-d configuration is as follows:
```json
{
    "d.neverUseDub": true,
    "d.manyProjectsAction": "load",
    "d.projectImportPaths": [
        "..",
        "../dependency",
    ],
}
```

Thanks a lot!
