### ISSUE TITLE
Snippets don't show up i VS Code

### ISSUE THREAD

**Issue by aberba** [Pure-D/code-d#315]
I'm snippets for things like `void main()`, `int main()` to show up as I type. I think I remember it was once available. Not sure if its been remove or it a bug or something.

**Comment by WebFreak001** [comment]
they are integrated into the auto completion engine now, do you have stable (or nightly or beta) serve-d and does autocompletion otherwise work?

**Comment by aberba** [comment]
Using the lastest in vs code stable. I meant snippets as in you type something, press tab and code snippets gets inserted.

**Comment by WebFreak001** [comment]
the snippets are context aware now, where are you trying to use them? Can you give some example code?

**Comment by aberba** [comment]
Say generate a `main()` function in an empty file.

**Comment by WebFreak001** [comment]
![working code-d snippets](https://user-images.githubusercontent.com/2035977/85506114-093d1d00-b5f0-11ea-93f9-173aff2a3583.png)

works fine

**Comment by aberba** [comment]
That's weird.

**Comment by WebFreak001** [comment]
send logs pls

**Comment by aberba** [comment]
Its resolved, its working now. Not sure why though.
