### ISSUE TITLE
Support dub.json not in root workspace

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#321]
I have a folder structure like this opened in Visual Studio Code:

```
.pipeline
- ...
cfg
- ...
d
- source
-- app.d
- dub.json
.dockerignore
.gitignore
Dockerfile
Jenkinsfile
...
```

The D coding including the `dub.json` is within its own folder `d`. This causes errors while e.g. executing CTRL+S in `dub.json`.
A popup is shown `Could not upgrade dub.json`.
In log I can see the issue `No package file found in ...`. Actually it tries to access `dub.json` in the root folder and not in the
folder `d`.

Update: Actually almost nothing works if the dub project is within a sub folder of the workspace. No code-completion / code navigation...

**Comment by andre2007** [comment]
As side information, also code coverage highlight is not working in case, the d coding (`dub.json`, `source`, `*.lst`) is in a sub folder.

**Comment by andre2007** [comment]
@WebFreak001 
Today I saw there is config option `d.extraRoots` with the description `Array of workspace-relative (or absolute) folders to force start a project instance it`.
I thought by using this config option (on workspace level), I can set the folder `d` as the D project root folder. But it doesn't work. Is my understanding correct, or does this config option has another meaning?

**Comment by WebFreak001** [comment]
actually should already work, weird it doesn't

**Comment by andre2007** [comment]
@WebFreak001 
I did some more investigations. The issue is related to the fact that I use Dev Containers. I created a separate issue: #352

**Comment by WebFreak001** [comment]
I think this is actually problematic in some cases, but if you have one, please open another issue with reproduction case / detailed description.
