### ISSUE TITLE
Publish code-d on open-vxs.org (for VSCodium, Eclipse, …)

### ISSUE THREAD

**Issue by Marko10-000** [Pure-D/code-d#328]
Can Code-D be published on open-vsx.org too? It's annoying to download the binary from the Microsoft store and install it manually. I use it in the flatpak version of VSCodium (without the trackers, additionally closed sourced added things to the build, … from Microsoft).
Thanks.
Link: https://open-vsx.org (maintained by the Eclipse Foundation).

**Comment by WebFreak001** [comment]
thanks for the suggestion, I didn't know about that one

**Comment by WebFreak001** [comment]
done: https://open-vsx.org/extension/webfreak/code-d

gonna make a CI step for this eventually and use GitHub releases for more transparent releasing

**Comment by WebFreak001** [comment]
CI done
