### ISSUE TITLE
Dub dependencies: Preview README.md broken for sub packages

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#332]
While clicking on the network symbol left to `d-unit` the "Preview README.md" opens.
This does not work for `vibe.d:tls` or the other sub packages. I assume some
specific logic is missing to support sub packages.

![image](https://user-images.githubusercontent.com/1451047/95595348-5a143c80-0a4c-11eb-95f7-9106fa5d7f24.png)

**Comment by WebFreak001** [comment]
made it possible to view other files than README on ~master now

Subpackages should have already worked but they probably just didn't have a README associated with them. Now code-d shows an error message in this case:

![no viewable files error message](https://wfr.moe/f6iIEZ.png)
