### ISSUE TITLE
Wrong linter for syntax

### ISSUE THREAD

**Issue by RUSshy** [Pure-D/code-d#336]
I have installed code-d from vscode extention market

The first thing i noticed was the theme was displaying wrong colors, so i enabled the inspector: 

![image](https://user-images.githubusercontent.com/18348637/100688759-5b465380-3383-11eb-9e42-263b7bf4627a.png)

And the first thing i noticed was:

![image](https://user-images.githubusercontent.com/18348637/100689041-f50e0080-3383-11eb-9607-57f178af3936.png)

As you can see here, it should be ``entity.name.struct.d`` since that is not a function

The one side effect of this is themes will show incorrect coloring

**Comment by RUSshy** [comment]
For comparison DLS one:

![image](https://user-images.githubusercontent.com/18348637/100689437-c3e20000-3384-11eb-9f83-88edf24a9588.png)

**Comment by WebFreak001** [comment]
it's not possible to determine correctly if it's a type or a function there. Instead of hardcoding just the D-style coding conventions, which would just make you believe that something is a type because of the casing, we would want to inspect it through DCD or a dmd frontend. See #299
