### ISSUE TITLE
synchronized highlighting

### ISSUE THREAD

**Issue by dd86k** [Pure-D/code-d#339]
Relates to #288

`synchronized` particularly breaks the highlighting especially in a switch/case. Untested against Laurent's dlang extension.

```
__gshared int test;
void main(string[] args) {
	synchronized ++test;
	switch (args.length) { // <- broke
	case 0:
		synchronized ++test;
		break; // <- broken, including this comment
	default: // <- broken, including this comment
	}
}
```

**Comment by WebFreak001** [comment]
current code-d ~master highlighting:
![code highlighting](https://wfr.moe/f63DCu.png)

**Comment by dd86k** [comment]
So is 0.23.0 coming out at least by 2022

**Comment by WebFreak001** [comment]
I don't want to promise anything, just soon™ :)

(jk, yes expect it actually soon)

**Comment by dd86k** [comment]
Is 0.23 waiting on something in particular? I could maybe be of help.

Another random example for fun:
![image](https://user-images.githubusercontent.com/8390674/103483126-3d6d7380-4db3-11eb-96d9-a242fb3c8579.png)

**Comment by WebFreak001** [comment]
the master branch contains unfinished unittest integration with test explorer, just need to finish that

**Comment by WebFreak001** [comment]
0.23.x released
