### ISSUE TITLE
Writing dot character in a comment triggers auto-completion

### ISSUE THREAD

**Issue by dejlek** [Pure-D/code-d#347]
One of the most annoying issues with code-d is when you are typing a comment and press `.` - it triggers auto-completion.

For an example start writing a line like: `/* To reproduce do this.` The moment you press the dot the auto-completion combobox appears... This is not annoying to people rarely comment their code, but I write lots of comments and document my modules, functions, classes and struct quite extensively.

This happens even if the comment is enclosed. So if you edit the following line `/* To reproduce do this */` and add dot, it will do the same.

**Comment by WebFreak001** [comment]
can't reproduce with latest serve-d version

try updating serve-d to beta or nightly using `"d.servedReleaseChannel": "nightly"`

**Comment by dejlek** [comment]
OK, no worries! I can wait for the next release! :) Thanks!

**Comment by schveiguy** [comment]
I ran into this as well. Updating to nightly does seem to fix it. When will the release happen?

**Comment by dejlek** [comment]
> I ran into this as well. Updating to nightly does seem to fix it. When will the release happen?

I am waiting too. :)

**Comment by WebFreak001** [comment]
released
