### ISSUE TITLE
Plugin not working in dev container

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#352]
In Visual Studio Code on Windows I use the dev container feature to run VSC on linux. I attached the dev container folder.
Almost nothing is working, no code completion / navigation ...
There are some strange values in the logs:

```
Params: {
    "settings": {
        "d": {
            "servedPath": "/root/.code-d/bin/serve-d",
            "stdlibPath": null,
            "dcdClientPath": "/root/.code-d/bin/dcd-client",
            "dcdServerPath": "/root/.code-d/bin/dcd-server",
            "dubPath": "dub",
            "dlsPath": "C:\\Users\\D0\\AppData\\Local\\dub\\packages\\.bin\\dls-latest\\dls.exe"
```

`stdlibPath` is null and als `dlsPath` points to the windows location instead to a linux location.
The full log is also contained in the zip archive. 

[devcontainer.zip](https://github.com/Pure-D/code-d/files/6230526/devcontainer.zip)

**Comment by WebFreak001** [comment]
dlsPath is unrelated to code-d/serve-d (you just have it in your settings it seems)

stdlibPath being null is OK, it will try to autodetect then

Reopen if this is still not working, I'm pretty sure at least in WSL it is working properly now.
