### ISSUE TITLE
Add manual "build-on-save" config option for triggering dub build

### ISSUE THREAD

**Issue by GavinRay97** [Pure-D/code-d#353]
```json
{
  "d.buildOnSave": {
    "type": "boolean",
    "default": false,
    "description": "Execute build task from tasks.json file on save.",
    "scope": "resource"
  }
}
```
```ts
  vscode.workspace.onDidSaveTextDocument(
    (document: Document) => {
      if (document.languageId) != "D"
        return
      if (!vscode.workspace.getConfiguration("d").getBool("buildOnSave"))
        return
      vscode.commands.executeCommand("workbench.action.tasks.build")
    },
    null,
    subscriptions
  )
```

**Comment by WebFreak001** [comment]
this seems out-of-scope for code-d and more like a general extension that probably already exists on the marketplace.

**Comment by GavinRay97** [comment]
That's fair -- assuming that an external extension will still trigger `code-d`'s problem matchers for compiler errors then that's probably a better option.

I just asked for this because currently the `dub build` integration for linting doesn't work, only manual builds report errors

**Comment by WebFreak001** [comment]
for the build tasks code-d ships with a problem matcher which you can enable with `"problemMatcher":["$dmd"]`

**Comment by GavinRay97** [comment]
Ah -- got it! Closing =)
