### ISSUE TITLE
Sort completion by kind type

### ISSUE THREAD

**Issue by RUSshy** [Pure-D/code-d#354]
Take this example:

![image](https://user-images.githubusercontent.com/18348637/113610373-50f7d700-964d-11eb-8883-efd2d571ca3d.png)

It is very hard to know what are the fields/functions available on first sight, i have to decipher and manually filter out things

In comparison in rider, it's very easy to find what you want (fields/functions for the struct/class)

![image](https://user-images.githubusercontent.com/18348637/113610649-b3e96e00-964d-11eb-9fd9-ec07f3c42a9f.png)

![image](https://user-images.githubusercontent.com/18348637/113610569-9a482680-964d-11eb-91d2-c996a1bebee1.png)

I had this suggestion a while ago for DLS, wich they fixed, so maybe we could take their code?

VSCode also seems to only show type information for the first line in the popup, in sublime text it shows it for all lines, maybe a setting to set?

https://github.com/d-language-server/dls/issues/51

Commit: https://github.com/d-language-server/dls/commit/6a9d6d246e8ad6a155e9d2e022d08fa3e5ef311b

**Comment by WebFreak001** [comment]
already on serve-d nightly/beta? this has been in for a long time

**Comment by RUSshy** [comment]
I am using nightly, i don't remember seeing this option, i'll check again

**Comment by WebFreak001** [comment]
oh it's not an option, it's just there. However it's not as sorted as in your screenshot, it does group some things.

See https://github.com/Pure-D/serve-d/blob/master/source/served/commands/complete.d#L81

**Comment by RUSshy** [comment]
Found a bug: https://github.com/Pure-D/serve-d/pull/126

Now to figure out proper rule for sorting things

Also would be nice to have an option in vscode, so people could choose between sort A-Z or sort by Completion Kind
