### ISSUE TITLE
Wrong syntax highlight

### ISSUE THREAD

**Issue by trikko** [Pure-D/code-d#36]
```d
enum Blah(T) = 
   true;
```

these two lines broke syntax highlight (following lines are not highlighted)

**Comment by trikko** [comment]
This line too:
```d
hello.world(`("`);
```

**Comment by trikko** [comment]
in / body:

```d
int t()
in { assert(0); }
body
{
   return 0;
}
```

**Comment by WebFreak001** [comment]
i think we will just rewrite it, so it won't try to guess the current scope and just highlight statically

**Comment by trikko** [comment]
I hope so :) Keep up the good work!

**Comment by trikko** [comment]
Things doesn't work now:

```d
// wrong syntax highlight
@property hello() { return 1; }

// right
@property int hello() { return 1; }  
```

```d
// wrong
mycustomstruct* hello() { }

// right
mycustomstruct hello() { }
```

**Comment by WebFreak001** [comment]
maybe i should completely remove highlighting function names. Why are we even doing that?

**Comment by trikko** [comment]
It's easier to see functions declarations from function calls and other things.

anyway also:

```d
private mycustomstruct hello;
// vs
private mycustomstruct* hello;
```

**Comment by WebFreak001** [comment]
the syntax could use some improvements

**Comment by aka-demik** [comment]
Plus one example:
```D
static immutable {
	struct StaticBuf {
		string fileCont;
		string linkName;
		string mimeType;
	}

	StaticBuf[] m_staticBufs = [
		StaticBuf(import("favicon.png"), "/favicon.png", "image/png"),
		StaticBuf(import("ys_logo.png"), "/ys_logo.png", "image/png")
	];
}
```
vs code:
![default](https://cloud.githubusercontent.com/assets/5939623/15885954/f0b4c5d6-2d62-11e6-81aa-111f70ab8b22.PNG)
