### ISSUE TITLE
Building dcd from source is failing

### ISSUE THREAD

**Issue by andre2007** [Pure-D/code-d#360]
With latest beta, dcd is built from source. In the code-d installer logs there are error messages because msgpack-d 1.0.1 cannot be found.
The solution is easy, just execute in console `dub fetch msgpack-d@1.0.1`. 

But I wonder whether something in the installation script is missing, I am also unsure now whether this issue belongs in this repository or into the DCD repository...

**Comment by WebFreak001** [comment]
sounds like a temporary / machine specific issue for you, does it happen on other machines?

**Comment by andre2007** [comment]
I haven't tried yet, but also dub build via console is failing. 
I get it also working by changing dub.sdl of dcd:common package. It has a fixed version dependency to "1.0.1". By changing it to "~>1.0.1" the build is working.

**Comment by andre2007** [comment]
You are right, I tried it on another computer . There it is working fine. It is a specific computer issue.
