### ISSUE TITLE
VSCode does not fully recognize code-d

### ISSUE THREAD

**Issue by AlexanderZhirov** [Pure-D/code-d#374]
```
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-04T20:38:29+02:00
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
ОС: Solus 4.3 Fortitude, Linux x64 5.14.16-204.current
```
Unable to use debugging. VSCode does not recognize the code-d type, as a result, it is not possible to create a debugging configuration.
I did everything according to the [instructions](https://github.com/Pure-D/code-d/blob/master/docs/debugging.md).
[Here is a demonstration of my actions.](https://www.youtube.com/watch?v=m9F9FSKnBxU)
It can be seen that the assembly goes without problems, but debugging does not work.

![2021-11-07_20-20](https://user-images.githubusercontent.com/37277056/140655018-1e2f99de-114a-4052-9cbb-a31d1da116c3.png)

![2021-11-07_20-18](https://user-images.githubusercontent.com/37277056/140655021-c0d365d2-2164-4ac3-a92e-20fe33c04118.png)

**Comment by WebFreak001** [comment]
the instructions you linked apply to master - the extension on the marketplace does not have this feature yet released

**Comment by AlexanderZhirov** [comment]
> the instructions you linked apply to master - the extension on the marketplace does not have this feature yet released

I tried to build extension from the source code - but I got a few errors during the build. How can I use an extension that will be correct?

**Comment by WebFreak001** [comment]
what errors did you get? it's building fine for me

**Comment by AlexanderZhirov** [comment]
> what errors did you get? it's building fine for me

 ```
~/Documents  git clone https://github.com/Pure-D/code-d.git
Клонирование в «code-d»…
remote: Enumerating objects: 2615, done.
remote: Counting objects: 100% (377/377), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 2615 (delta 217), reused 254 (delta 118), pack-reused 2238
Получение объектов: 100% (2615/2615), 10.93 МиБ | 274.00 КиБ/с, готово.
Определение изменений: 100% (1630/1630), готово.
 ~/Documents  cd code-d   
 ~/Documents/code-d   master  npm install

added 264 packages, and audited 265 packages in 8m

1 package is looking for funding
  run `npm fund` for details

13 vulnerabilities (10 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
 ~/Documents/code-d   master ±  tsc -p .
node_modules/@types/jsdom/ts3.1/index.d.ts:175:31 - error TS2552: Cannot find name 'HTMLAppletElement'. Did you mean 'HTMLTableElement'?

175     HTMLAppletElement: typeof HTMLAppletElement;
                                  ~~~~~~~~~~~~~~~~~

  ../../../../usr/lib64/node_modules/typescript/lib/lib.dom.d.ts:8527:13
    8527 declare var HTMLTableElement: {
                     ~~~~~~~~~~~~~~~~
    'HTMLTableElement' is declared here.

src/extension.ts:533:15 - error TS2571: Object is of type 'unknown'.

533    if (err && err.code == "ENOENT") {
                  ~~~

src/extension.ts:549:22 - error TS2571: Object is of type 'unknown'.

549    } else if (err && err.code == "EACCES") {
                         ~~~

src/extension.ts:551:22 - error TS2571: Object is of type 'unknown'.

551    } else if (err && err.code) {
                         ~~~

src/extension.ts:552:116 - error TS2571: Object is of type 'unknown'.

552     return await vscode.window.showErrorMessage(name + " from setting " + fullConfigName + " failed executing: " + err.code, reinstallBtn, userSettingsBtn).then(defaultHandler);
                                                                                                                       ~~~

src/extension.ts:651:36 - error TS2571: Object is of type 'unknown'.

651      getInstallOutput().appendLine(e.toString());
                                       ~


Found 6 errors.
```

**Comment by WebFreak001** [comment]
your typescript compiler might not be the version of the repository - try using `npx tsc` instead of `tsc` to make node use the locally installed tsc

**Comment by AlexanderZhirov** [comment]
> your typescript compiler might not be the version of the repository - try using `npx tsc` instead of `tsc` to make node use the locally installed tsc

Oh, yes!!! I did it!!!

Everything was successfully compiled and installed! Debugging works! I just can't run DUB debugging, but only a specific file

![2021-11-07_22-19](https://user-images.githubusercontent.com/37277056/140658753-b4db23a3-07d9-4761-a3e7-792dc2ee8620.png)

**Comment by WebFreak001** [comment]
adjusted the README

about the dub debugging I need to check that again because I'm not sure if I have had it fully finished before.

You might also just be missing the latest serve-d version for it to work (change your user setting d.servedReleaseChannel to nightly, then reload the window and it will download the latest commit)

**Comment by AlexanderZhirov** [comment]
> You might also just be missing the latest serve-d version for it to work (change your user setting d.servedReleaseChannel to nightly, then reload the window and it will download the latest commit)

Yes, it helped. Everything works!

The only thing is that I have the parameter `"TargetPath" : "bin"` set in my dub-config, which is why I had to add
`"cwd": "${command:dubWorkingDirectory}/bin",`

**Comment by WebFreak001** [comment]
ok marking this as closed then
