### ISSUE TITLE
No syntax highlight for the D programming language in Markdown's fenced code blocks

### ISSUE THREAD

**Issue by robertkovacs** [Pure-D/code-d#387]
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

code-d version: 0.23.2

The easiest to demonstrate the issue is opening the attached markdown file (test.md). When open in VSCode, there is syntax highlight available for the c++ code block, but no syntax highlight for the 'd' code block.

Opening the Markdown preview by clicking the 'Open Preview to the Side' icon in the tab bar gives a preview with both fenced code blocks syntax-highlighted properly - see the attached screenshot for an illustration.

Expected behavior: the fenced code block containing 'D' code should have proper syntax highlight in the raw markdown source view as well, not only in the preview.

I guess the procedure described [here](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example) should be followed by code-d as well.

[test.md](https://github.com/Pure-D/code-d/files/7695672/test.md)
<img width="1440" alt="Screen Shot 2021-12-10 at 23 02 05" src="https://user-images.githubusercontent.com/32719856/145647116-cbd87b8f-2e50-487b-9e07-ff78c0dc6135.png">

**Comment by WebFreak001** [comment]
I'm not sure if this is even extensible or if this is hardcoded into the markdown extension.

**Comment by robertkovacs** [comment]
First of all, thank you for code-d, and thank you for reacting so quickly. 

The last sentence in the description contains a link which - after only skimming through - suggested a procedure extensions should follow - or at least this is what I understood. I guess I will check it out more thoroughly and report back what I've found.

**Comment by WebFreak001** [comment]
ah sorry yeah that looks reasonable, can add that

**Comment by robertkovacs** [comment]
Well, it worked. After manually tweaking the installed code-d extension files according to that description, I got nice syntax highlighting in fenced code blocks too.

Attached a rough diff just to demonstrate the idea.

[code-d.diff.txt](https://github.com/Pure-D/code-d/files/7695876/code-d.diff.txt)
.

**Comment by WebFreak001** [comment]
thanks! changed a few small things to look more like the example repository you sent and pushed it to code-d master. (made you the author of the commit)
