### ISSUE TITLE
How to build and lint?

### ISSUE THREAD

**Issue by luismarques** [Pure-D/code-d#39]
The page at <https://wiki.dlang.org/Editors> says that code-d supports building and linting, but I don't know how to do that (I don't have much experience with Visual Studio Code at the moment), and there are no instructions for that on the code-d page / README.

**Comment by WebFreak001** [comment]
If it works without any problems and if you have dub and dscanner installed you can just save the file and by default it will find any errors and lint stuff.

At the bottom in the panel there are build/run buttons that will call dub. You can also change the configuration which also affects import paths & the building

**Comment by WebFreak001** [comment]
hm i guess we could add it to the readme though, but its basically just like in any other language except for the building. Probably just the building

**Comment by luismarques** [comment]
I have dub and dscanner installed, and yet no errors and warnings about my code appear. The extension / editor also don't notify me about anything related to d-code being missing or not operational, such that it gives a strong impression that d-code does not provide building and linting.

BTW, regarding "At the bottom in the panel there are build/run buttons that will call dub", do you mean the error and warning buttons (cross and warning traffic sign)? Those just show a popup that says "No errors or warnings". Shouldn't code-c just make it say that no error and warning info is available, or something like that?

Regarding "You can also change the configuration which also affects import paths & the building":

1. This should be documented in d-code, for VS Code newbies, IMO
2. Couldn't code-d (or workspace-d) be smarter and get the proper D import paths from, say, my `/usr/local/etc/dmd.conf`? The default path is wrong.
3. In any case, I added an override to my configuration, such that it matched my dmd.conf:

```
// Place your settings in this file to overwrite the default settings
{
    "d.stdlibPath": [
        "/usr/local/Cellar/dmd/2.071.0/include/dlang/dmd"
    ]
}
```

...and yet I get no completion after `import std.` (it does not find, say, bitmanip).

BTW, in the installation instructions where it says "Launch VS Code Quick Open (⌘+P), paste the following command, and type enter.", after pasting the command the first autocomplete was something for docker, so pressing enter installed something totally different. This idiocy of Visual Studio Code became even more confusing because there is very little feedback about something have happened between pressing enter and the installation being complete. In any case, it would probably be a good idea to tweak the code-d installation instructions so that it does not say to just press enter.

**Comment by WebFreak001** [comment]
those are not my installation instructions, vscode adds them with issues but they don't care about my issue! https://github.com/Microsoft/vscode/issues/4456

However if there is no play & build button in the bottom bar then workspace-d failed to initialize or start or you are not in a dub repository. Or it just takes way too long.

If you can format the code however it should fully work. Ensure code formatting works (with dfmt installed), otherwise it's an issue with workspace-d

**Comment by WebFreak001** [comment]
Probably duplicate of https://github.com/Pure-D/code-d/issues/38 in this case
