### ISSUE TITLE
[feature] Add support of custom arch

### ISSUE THREAD

**Issue by sr-tream** [Pure-D/code-d#404]
Since 2018 DUB may pass `-mtriple` targets to ldc2 from `-a`/`--arch=` argument, like `dub build -ax86_64-windows-msvc --complier=ldc2`.

It would be great if I can use `x86_64-windows-msvc` for building from vscode instead of usage terminal

**Comment by WebFreak001** [comment]
already supported in current nightly serve-d

**Comment by WebFreak001** [comment]
pre-release available, next code-d release will also expose this better.
