### ISSUE TITLE
Incorrect links in documentation containing an `@` symbol

### ISSUE THREAD

**Issue by HuskyNator** [Pure-D/code-d#406]
It seem the tooltip shown for functions containing documentation does not like it when `@`'s are included in a (bare?) URL's

Using a permalink to the dlang forum for example:
```d
module app;
import std.stdio;

/** 
 * https://forum.dlang.org/post/rjnywrpcsipgkronwrrc@forum.dlang.org
 */
void main(){
	writeln("Test");
}
```
Hovering will show (the hyperlink is wrong when clicked too, of course):
![image](https://user-images.githubusercontent.com/17416803/164510210-e8968189-cc4f-46d8-926f-5f5667092509.png)

The fact `https:` is interpreted as a field in the documentation is also pretty interesting.
(See #405 for this.)

**Comment by WebFreak001** [comment]
probably just #405 is an issue, the link detection is not part of code-d, so closing this in favor of that issue.
