### ISSUE TITLE
syntax highlighting: types are not recognized

### ISSUE THREAD

**Issue by ryuukk** [Pure-D/code-d#412]
Types are not recognized, so themes doesn't work on them

![image](https://user-images.githubusercontent.com/44361234/176023290-eb929f39-7568-4bde-8ab3-074d132fce5c.png)

![image](https://user-images.githubusercontent.com/44361234/176023328-afaa9604-622a-4611-b95e-aec00eaaf2c0.png)

I managed to make them working with this syntax code:

One problem though, it doesn't work with lower case types

If anyone is a regex god, please save me :D

```
// ok
Type type;
module.Type type;

// not working
type type;
mu.type type;

```

```json
      {
        "name": "meta.variable.d",
        "patterns": [

            {
                "_": "also stuff like mu.Context ctx;",
                "match": "\\b[A-Z][a-zA-Z0-9]*\\b",
                "captures": {
                  "0": {
                      "name": "entity.name.type.d"
                  }
                }
            },
            
            {
                "_": "constants all upper case",
                "match": "\\b[_A-Z][_A-Z0-9]+\\b",
                "name": "variable.constant.d"
            },


            {
                "_": "everything else?",
                "match": "\\b[_a-zA-Z][_a-zA-Z0-9]*\\b",
                "name": "variable.d"
            }
        ]
      },
```

**Comment by WebFreak001** [comment]
not planning to overcomplicate the regex like this, going for the semantic highlighting.

closing as duplicate #299
