### ISSUE TITLE
I install all dependency but it didn't take effect

### ISSUE THREAD

**Issue by magicdmer** [Pure-D/code-d#43]
Platform:
os:win7 x64
vscode:1.1.1

I write user setting like follow:
```json
{
    "editor.fontSize": 14,
    
    "d.dcdClientPath": "E:/D/dcd-client.exe",
    
    "d.dcdServerPath": "E:/D/dcd-server.exe",
    
    "d.dfmtPath": "E:/D/dfmt.exe",
    
    "d.workspacedPath": "E:/D/workspace-d.exe",
    
    "d.dscannerPath": "E:/D/dscanner.exe",
    
    "d.enableAutoComplete": true,
    
    "d.enableLinting": true,
    
    "d.enableDubLinting": true
}
```
but when i open a  test.d file,  the autocompletion had no effect , I type string.  , it didn't display any tips. I found the dcd-client.exe dcd-server.exe workplace-d.exe ... is not running. 

I use vscode command : code-d:restart DCD Server,  it display a error message like:
"No handler found for the command: 'code-d.restartServer'.An extension might be missing an activation event."

what happened , i hope someone tell me .

**Comment by WebFreak001** [comment]
did you open a .d file or does your project have a dub.json/dub.sdl in the root directory? The plugin only starts if any of those happens

**Comment by WebFreak001** [comment]
Also check the developer tools for logs from code-d (Ctrl-Shift-P -> `Toggle developer tools`)

**Comment by magicdmer** [comment]
Thank you for your answer, There is no some toolbar appear at the bottom when i open test.d . 
test.d is a source file in visualD project.  

I  check the Toggle developer tools and found that it remind me to open a folder but not a singe source file ,so i open the ConsoleApp1 project folder made by VisualD.  
![one](http://s32.postimg.org/plyokggjp/image.png)

But it still not autocomplete,so i  input command "code-d:Reload import paths", the log display:

```
[Extension Host] Initialized code-d
[Extension Host] fsworkspace is ready
[Extension Host] DScanner is ready
[Extension Host] Dfmt is ready
[Extension Host] DlangUI is ready
[Extension Host] provideHover
[Extension Host] provideCompletionItems
[Extension Host] lint
Could not update imports. dub might not be initialized yet!
[Extension Host] WorkspaceD Debug: object.Exception@C:\Users\Administrator\AppData\Roaming\dub\packages\dub-0.9.25-rc.1\source\dub\package_.d(186): No package file found in .\, expected one of dub.json/dub.sdl/package.json
----------------
0x00409599 in pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], uint, const(char[])) at E:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(416)
0x00409542 in pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], uint) at E:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(364)
0x004A3809 in D3dub8package_7Package4loadFS3dub8internal10vibecompat4inet4path4PathS3dub8internal10vibecompat4inet4path4PathC at C:\Users\Administrator\AppData\Roaming\dub\packages\dub-0.9.25-rc.1\source\dub\package_.d(191)
0x004A8DEA in D3dub14packagemanager14PackageManager16getOrLoadPackageMFS3dub8internal10vibecompat4inet4path4Path
0x0047D978 in void workspaced.com.dub.start() at D:\CodeLibrary\workspace-d\source\com\dub.d(73)
0x0047D9A9 in void workspaced.com.dub.restart() at D:\CodeLibrary\workspace-d\source\com\dub.d(81)
0x0047D9D2 in void workspaced.com.dub.update(void delegate(object.Throwable, std.json.JSONValue)) at D:\CodeLibrary\workspace-d\source\com\dub.d(100)
0x004283AD in D10workspaced3app45__T16handleRequestModS2010workspaced3com3dubZ16handleRequestModFiS3std4json9JSONValueKAS3std4json9JSONValueKiKbKbxDFC6object9Throwable
0x00425ED2 in void workspaced.app.handleRequest(int, std.json.JSONValue) at D:\CodeLibrary\workspace-d\source\app.d(272)
0x004267DA in _Dmain at D:\CodeLibrary\workspace-d\source\app.d(378)
0x00576EA7 in D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv
0x00576E6B in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
0x00576D6C in _d_run_main
0x004315FC in main at D:\CodeLibrary\workspace-d\source\api.d(7)
0x005DA795 in mainCRTStartup
0x745D3744 in BaseThreadInitThunk
0x77089E54 in RtlSetCurrentTransaction
0x77089E1F in RtlSetCurrentTransaction

[Extension Host] Object {error: true, exception: "object.Exception@C:\Users\Administrator\AppData\Ro…ransaction↵0x77089E1F in RtlSetCurrentTransaction", msg: "No package file found in .\, expected one of dub.json/dub.sdl/package.json", request: Object}
[Extension Host] [Object, Object]
[Extension Host] Resolve
[Extension Host] [Array[2]]
[Extension Host] WorkspaceD Debug: Server: 2016-05-19T23:27:10.553:C:\Users\Administrator\Desktop\dcd\src\server\server.d:main:78 Starting up...



[Extension Host] WorkspaceD Debug: Server: 2016-05-19T23:27:10.822:C:\Users\Administrator\Desktop\dcd\dsymbol\src\dsymbol\conversion\first.d:visit:379 Could not resolve location of module 'ldc\intrinsics'



[Extension Host] rejected promise not handled with 1 second
Something Error. view log for detail.
[Extension Host] WorkspaceD Debug: Server: 2016-05-19T23:27:11.386:C:\Users\Administrator\Desktop\dcd\dsymbol\src\dsymbol\conversion\first.d:visit:379 Could not resolve location of module 'gcc\builtins'



[Extension Host] WorkspaceD Debug: Server: 2016-05-19T23:27:13.993:C:\Users\Administrator\Desktop\dcd\src\server\server.d:main:116 Import directories:


Server:     D:/MyProject/DWorkPlace/ConsoleApp1/ConsoleApp1


Server:     E:/D/dmd2/src/druntime/import


Server:     E:/D/dmd2/src/phobos


Server: 
[Extension Host] WorkspaceD Debug:     E:/D/dmd2/src/druntime/import


Server:     E:/D/dmd2/src/phobos


Server: 2016-05-19T23:27:13.993:C:\Users\Administrator\Desktop\dcd\src\server\server.d:main:122 24466 symbols cached.


Server: 2016-05-19T23:27:13.994:C:\Users\Administrator\Desktop\dcd\src\server\server.d:main:123 Startup completed in 3440.13 milliseconds.



[Extension Host] DCD is ready
```

dcd-server.exe and workplace-d.exe is running ok

**Comment by WebFreak001** [comment]
Oh somehow the extension thinks there is a dub.json/dub.sdl/package.json in the project root. If there is a dub.json file and it has some big dependencies, it could take some time for the plugin to start up. Otherwise if it doesn't have dependencies it should start nearly instantly. Does it work or is there DCD output if you wait about 10-20 seconds?

**Comment by magicdmer** [comment]
At first there is only workplace-d.exe running, after i input command "code-d:Reload import paths", the dcd-server.exe begin to run,  i try to wait some times , but it had no effect. The project have no dub.json/dub.sdl/package.json.  I use sublimeText and DKit dcd-server,  it works well, the tips display fast.

**Comment by WebFreak001** [comment]
does it work if you set `"d.neverUseDub": true` in your vscode config?

**Comment by magicdmer** [comment]
I set that and it‘s no use, the toolbar didn't appear, the log still display dub error when i Reload import paths. It's a strange question.

**Comment by WebFreak001** [comment]
I am not sure why reload import paths even works, its only supposed to be used with dub projects and it should only work if you are using dub. Otherwise you should use the `restart server` command, but that one won't work either if dcd doesn't start in the first place

**Comment by WebFreak001** [comment]
No keep it open until its resolved

**Comment by WebFreak001** [comment]
I will try to find a way to replicate it

**Comment by WebFreak001** [comment]
Update workspace-d and try again, it should be fixed now

**Comment by magicdmer** [comment]
I git clone the newest workplace-d sourcecode and build it , but as before , have no effect.

**Comment by magicdmer** [comment]
dub build

**Comment by WebFreak001** [comment]
You need to build it with LDC on windows. Try running the install script or do `dub build --compiler=ldc2` (or ldc)

**Comment by magicdmer** [comment]
I use dub build --compiler=ldc2 , but as before，have no effect. maybe my luck is not very good

**Comment by WebFreak001** [comment]
After you have built `workspace-d` with LDC and properly configured vscode to use it or replaced the old file, is the debug console in vscode any different?

**Comment by magicdmer** [comment]
have no any defferent , the debug info is ok  like the picture above,  anytime i input ".", the number will increase，have no error。

**Comment by magicdmer** [comment]
I solved the problem,  i  forget to set the "d.stdlibPath" before, now ,it work well.
the biggest problem is that the workplace-d must build with ldc2.
