### ISSUE TITLE
$dmd problem matcher doesn't fail on "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by al1-ce** [Pure-D/code-d#440]
Basically in case of this error vscode build is considered success, which is misleading. Yet core dumped message doesn't appear in build log too

**Comment by WebFreak001** [comment]
can you share your build configuration?

**Comment by al1-ce** [comment]
You mean tasks.json?

**Comment by WebFreak001** [comment]
you said the build is considered success, do you mean it continues with things such as starting the debugger when using as preLaunchTask?
