### ISSUE TITLE
"vsce package" is now error.

### ISSUE THREAD

**Issue by Rayerd** [Pure-D/code-d#444]
![image](https://user-images.githubusercontent.com/586833/211158469-d54e1ed2-a549-4227-afd5-897d9dcb8490.png)
![image](https://user-images.githubusercontent.com/586833/211158627-4f119eb6-b93f-41af-8be1-26aed17476fe.png)

**Comment by WebFreak001** [comment]
outdated dependencies or typescript? Works fine here. Try these commands:

```
git pull
npm install
npx tsc
```

then, typescript compilation should have succeeded.

**Comment by Rayerd** [comment]
very sorry.
```
npm install
npx tsc -p .
vsce package
```
Worked fine, thank you.

![image](https://user-images.githubusercontent.com/586833/211183545-8bf391f2-6f91-4357-bf1d-6319ebbe8707.png)
