### ISSUE TITLE
Errors are not highlighted or underlined

### ISSUE THREAD

**Issue by BrainKicker** [Pure-D/code-d#445]
![изображение](https://user-images.githubusercontent.com/30545094/213926948-4e48ec8c-fcfd-4ec6-b0ca-ae03c76ad91b.png)

As you can see, some random symbols, which are undoubtedly an error from the point of view of the compiler, are not highlighted.

Why so and how can I turn on the highlighting?

I'm using Linux Mint 21.1 Vera, VSCode 1.74.3 x64 and latest version of code-d (from marketplace).

**Comment by WebFreak001** [comment]
currently with compiler issue finding there is a bug that will soon be fixed (https://github.com/dlang/dub/pull/2562)

However with that invalid syntax it should already show issues through dscanner / libdparse.

Try upgrading serve-d: in the user settings change d.servedReleaseChannel to beta or nightly, then reload the VSCode window

**Comment by BrainKicker** [comment]
I've changed d.servedReleaseChannel to nightly and now it shows some errors.

But for example for that code:

```d
void main() {
    a;
}
```

it doesn't highlight "a".

Is it the same problem with the compiler?

**Comment by WebFreak001** [comment]
ah yes that explains why it was behaving so randomly, but this behavior has now been fixed in the latest serve-d commit. Will be releasing a new beta and stable release soon.
