### ISSUE TITLE
Syntax highlighting inconsistency for semicolons preceding other tokens in the same line

### ISSUE THREAD

**Issue by SpaghettiBorgar** [Pure-D/code-d#448]
Semicolons that are not at the end of the line are highlighted differently than line-ending semicolons.
This seems to happen with tokens of any kind.

![image](https://user-images.githubusercontent.com/32263284/224510738-5fd8cbca-214c-4235-a6ca-fee53b579ab8.png)

**Comment by WebFreak001** [comment]
fixed in #bee4f03
