### ISSUE TITLE
Autocomplete fails in fresh Dub project with "document not found" error.

### ISSUE THREAD

**Issue by DenisBelmondo** [Pure-D/code-d#454]
System:

- lsb-release:
  - `DISTRIB_ID="ManjaroLinux"`
  - `DISTRIB_RELEASE="23.0.0"`
  - `DISTRIB_CODENAME="Ultima Thule"`
  - `DISTRIB_DESCRIPTION="Manjaro Linux"`
- Compiler (LDC2):
  - `binary    /usr/bin/ldc2`
  - `version   1.32.1 (DMD v2.102.2, LLVM 15.0.7)`
  - `config    /etc/ldc2.conf (x86_64-pc-linux-gnu)`

I am using the manual installation for testing and possible development purposes. This includes building DCD, serve-d, and code-d from scratch. Here are my steps:

- Clone and build DCD
  - ran `make ldc` in the DCD project root.
- Clone and build serve-d
  - ran `./release.sh` in the serve-d project root (that is, after creating and switching to this branch: https://github.com/Pure-D/serve-d/pull/322)
- Clone and build code-d with instructions similar to those outlined in README/installation:
  - cloned code-d not in `~/.vscode[-oss]/extensions`, but in the arbitrary path `~/Documents/vscode`
  - ran `npm install` and `npx tsc -p .`
  - ran `vsce package`
- Installed extension manually from resulting .VSIX file from previous step and restarted VSCode.
- Put the following in my own settings.json:

```
    "d.dubCompiler": "ldc2",
    "d.stdlibPath": "/usr/include/dlang/ldc",
    "d.dubPath": "/usr/bin/dub",
    "d.servedPath": "/opt/serve-d/serve-d",
    "d.dcdClientPath": "/opt/DCD/bin/dcd-client",
    "d.dcdServerPath": "/opt/DCD/bin/dcd-server",
    "d.aggressiveUpdate": false,
    "dfmt.braceStyle": "stroustrup",
    "d.dietContextCompletion": true,
    "d.servedReleaseChannel": "frozen",
    "serve-d.trace.server": "verbose"
```
- Closed VSCode.
- Created a new project at `~/Documents/d/testgame` with `dub init`.
- Opened folder with VSCode.
- Observed that autocomplete did not working when typing `import std.` even after hitting the key combination to trigger the dropdown.
- Observed that the same happens when trying to trigger symbol suggestions and function parameter hints.
- Went to the Output panel, under code-d & serve-d, here is the output: https://pastebin.com/P1AandDP (too long to put here).

**Comment by WebFreak001** [comment]
can you try again with this PR applied? (it's in master now) https://github.com/Pure-D/serve-d/pull/321

**Comment by DenisBelmondo** [comment]
Excellent, after that commit it seems to work like a charm. I got the import and function autocompletes and suggestions. Thanks!
