### ISSUE TITLE
Installing code-d on Apple M1 fails as it requires rdmd

### ISSUE THREAD

**Issue by pubnoconst** [Pure-D/code-d#479]
I am using an apple M1 chip laptop and I am trying to setup vs code for D development.
I have installed ldc2 1.38 and dub, but I cannot see any rdmd in the homebrew repo. I understand that dmd has not yet been ported to apple silicon, but does rdmd require dmd?
Subsequently, my machine is unable to compile code-d as it requires rdmd. 

Edit, it would appear that the ldc2 package in homebrew did not provide ldmd2. Sounds like an issue on my end. Feel free to close it. 

<details>
<summary>Log</summary>

Installing into /Users/u1/.vscode/extensions/webfreak.code-d-0.23.2/bin
> git clone --recursive https://github.com/Pure-D/serve-d.git serve-d
Cloning into 'serve-d'...
> git checkout v0.7.6
Note: switching to 'v0.7.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at fc9df49 v0.7.6, OpenSSL 3.2+ fix
> /opt/homebrew/bin/dub upgrade
   Upgrading project in /Users/u1/.vscode/extensions/webfreak.code-d-0.23.2/bin/serve-d/
             Not upgrading sub package in http
             Not upgrading sub package in lsp
             Not upgrading sub package in serverbase
             
Note: specify -s to also upgrade sub packages.
> /opt/homebrew/bin/dub build --compiler=ldc2
     Warning 
     Warning ## Warning for package serve-d, configuration unittest-optimized ##
     Warning 
     Warning The following compiler flags have been specified in the package description
     Warning file. They are handled by DUB and direct use in packages is discouraged.
     Warning Alternatively, you can set the DFLAGS environment variable to pass custom flags
     Warning to the compiler, or use one of the suggestions below:
     Warning 
     Warning debugInfo: Call DUB with --build=debug
     Warning optimize: Call DUB with --build=release
     Warning unittests: Call DUB with --build=unittest
     Warning 
     Warning Invalid source/import path: /Users/u1/.dub/packages/dfmt/0.14.1/dfmt/bin
     Warning Invalid source/import path: /Users/u1/.dub/packages/dscanner/0.11.1/dscanner/bin
     Warning Invalid source/import path: /Users/u1/.dub/packages/dcd/0.13.6/dcd/bin
     Pre-gen Running commands for dfmt
/bin/sh: rdmd: command not found
Error Command failed with exit code 127: rdmd "/Users/u1/.dub/packages/dfmt/0.14.1/dfmt/dubhash.d"
Failed to install serve-d (Error code 2)
</details>

**Comment by WebFreak001** [comment]
Try upgrading to serve-d nightly by setting the `d.servedReleaseChannel` setting in vscode (Ctrl-, for User Settings) to `nightly` - afterwards, reload the window with `Ctrl-Shift-P` -> `Reload Window` and let it automatically download the update.

**Comment by pubnoconst** [comment]
Switching to nightly fixed it. Thank you!
