### ISSUE TITLE
dub version issue persists after setting "dub path" variable

### ISSUE THREAD

**Issue by ziyuezzy** [Pure-D/code-d#487]
Dear developers and user community of code-D,

I encounter some dub version issues with code-D. For my dlang project, dub version  >=1.34.0 is required, and I have set 

`"dub path = /users/${me}/dlang/ldc-1.39.0/bin/dub"`

in my vscode preferences.

However, when opening the project directory, vscode still reports the following:

```
 Could not initialize dub for ,some project.. Falling back to limited functionality!
dub-1.26.1 does not comply with toolchainRequirements.dub specification: >=1.34.0
Please consider upgrading your DUB installation
```

It seems that code-d is still using dub-1.26.1 instead of the 1.39.0 that I specified in the preference?

Have anyone encountered similar problem, or any idea what went wrong?

Thank you in advance!!

**Comment by WebFreak001** [comment]
did you set the VSCode setting "d.dubPath"? Try setting it explicitly if it's not set

**Comment by WebFreak001** [comment]
oh also most importantly, make sure you are using serve-d nightly or beta

Try upgrading to serve-d nightly by setting the `d.servedReleaseChannel` setting in vscode (Ctrl-, for User Settings) to `nightly` - afterwards, reload the window with `Ctrl-Shift-P` -> `Reload Window` and let it automatically download the update.
