### ISSUE TITLE
Nightly build not available in TheiaIDE code-d 

### ISSUE THREAD

**Issue by leh103** [Pure-D/code-d#491]
In the TheiaIDE which uses the same code-d plugin as VS Code, the user is not able to select the nightly build of code-d in the plugin settings. Which is possible in VS code, but in the TheiaIDE the user is stuck using the current three year old code-d.

**Comment by WebFreak001** [comment]
are there no JSON configurations?

You should be able to set the setting `d.servedReleaseChannel` (Ctrl-, for User Settings) to `nightly` - afterwards, reload the window with `Ctrl-Shift-P` -> `Reload Window` and let it automatically download the update.

**Comment by leh103** [comment]
Thanks for the help. I didn't realize that TheiaIDE had the same settings as vs code. By the way in the TheiaIDE you can use ctrl+R to reload the window instead of going through the command palette.

This issue can be closed.

**Comment by fithisux** [comment]
> Thanks for the help. I didn't realize that TheiaIDE had the same settings as vs code. By the way in the TheiaIDE you can use ctrl+R to reload the window instead of going through the command palette.
> 
> This issue can be closed.

I did the above and switched to nightly. Though the plugin did not update in Theia.

Windows 10 x64, 1.57.100 version

**Comment by leh103** [comment]
You may have to close the IDE and restart it on Windows.
