### ISSUE TITLE
Format DDoc in documentation properly

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/code-d#51]
- [x] Remove surrounding `/** */` `/++ +/` `///`
- [x] Format properly
  - [x] Format sections (`Authors:`, `Bugs:`, `Params:`, etc.)
    - [x] Show documentation for parameters on parameters
  - [x] Embedded HTML
  - [x] Embedded/Inline Code
  - [x] Macros
    - [x] Predefined
    - [x] ~Ignore unknown~
  - [x] Escapes

**Comment by jonathanballs** [comment]
Hey, I would be interested in helping solve this issue (specifically param support). Would you be able to point me to where in the code I should start?

**Comment by WebFreak001** [comment]
@jonathanballs hi, cool that would be great!

The documentation in general is converted to markdown inside https://github.com/Pure-D/serve-d/blob/master/source/served/ddoc.d where I would also add helper functions to extract per function documentation.

The documentation is converted for autocompletion here: https://github.com/Pure-D/serve-d/blob/master/source/served/commands/complete.d#L485 - this one is shown inside the auto completion list when a symbol is active and should either show all or none of the parameters. I would prefer keeping all the documentation there because template types can also have documentation here and are never shown inside the calltips.

![https://wfr.moe/fzY2s8.png](https://wfr.moe/fzY2s8.png)
showing that autocompletion list

and for calltips here: https://github.com/Pure-D/serve-d/blob/master/source/served/commands/calltips.d#L23

The calltips are what you want to edit here (they are what pop up after pressing opening parenthesis or comma) - In line 29 it already extracts all the function parameters (which works pretty good for most common functions, sometimes it has issues though), where you can just pass an optional string for the documentation. (`opt("docs")`) This is where you could then use the extracted parameter documentation from the ddoc package you would need to implement. You could just look it up by symbol name because every parameter is optional in the docs.

![https://wfr.moe/fzYqT0.png](https://wfr.moe/fzYqT0.png)
calltips window

ParameterInformation definition: https://github.com/Pure-D/serve-d/blob/master/source/served/protocol.d#L1148

protocol.d contains all the language protocol types, so for documentation go here: https://microsoft.github.io/language-server-protocol/specification

**Comment by jonathanballs** [comment]
That was very kind of you to write such a detailed write up. I will take a look this evening when I have time. Thank you very much!

**Comment by WebFreak001** [comment]
parameters now also supported with Pure-D/serve-d@9cd565d
