### ISSUE TITLE
vs-code not working with loose files

### ISSUE THREAD

**Issue by TurkeyMan** [Pure-D/code-d#62]
I have code-d installed in vscode. I often write loose scripts in D using rdmd. They are not part of a 'project', and when I open them in vs-code, nothing works; goto-definition, auto-complete, etc.

Please make this workflow work in vs-code?

**Comment by TurkeyMan** [comment]
It's worth noting that these rdmd 'scripts' often have
```
#!/usr/bin/env rdmd
```
at the top, which is illegal D syntax, and needs to not confuse any of the tools...

**Comment by WebFreak001** [comment]
This works without any problems for me and all features are supported.

What does the file/folder structure in your project look like? It treats the auto completion as if the source directory would be directly your project path and not a subfolder. If you use a subfolder every module name needs to be prepended with that subfolder name.

Also can you send the log from the dev tools console? (Ctrl-Shift-P -> Toggle Developer Tools)

It contains the information what code-d and workspace-d are doing in your project and how they are initializing it.

**Comment by TurkeyMan** [comment]
No file/folder structure, no project or anything, just open a single loose `.d` file in vs-code, doesn't seem to work.
I'll try and get the log next time I'm at work.

No modules, infact, the file doesn't even have a `module` statement. It does have `#!/usr/bin/env rdmd` as the first line of the file though, which is invalid D code.

**Comment by WebFreak001** [comment]
yeah that setup works for me too

**Comment by TurkeyMan** [comment]
okay cool. i'll try and get the log on monday.

**Comment by TurkeyMan** [comment]
on a tangent, how's that .deb coming along? :P

**Comment by WebFreak001** [comment]
well i will start on that later

**Comment by WebFreak001** [comment]
Ah this happens when you don't have any folder open! (eg hit "close folder" before working)

I should be able to fix this then

**Comment by TurkeyMan** [comment]
Great! Though sadly, that work is finished now :)
