### ISSUE TITLE
Better syntax highlighting for D files

### ISSUE THREAD

**Issue by skl131313** [Pure-D/code-d#65]
Right now there is limited syntax highlighting, for example when declaring a variable, the type is not highlighted a different color. As well as enum values are not highlighted either. It would be nice to have these values highlighted if it is possible. 
![magic](https://cloud.githubusercontent.com/assets/8701667/17841196/24dc1f10-67e4-11e6-848e-ea736e1f244f.png)
In this case for the line of "Magic magic;", the type "Magic" should be highlighted. As well as "MY_ENUM_VALUE", different/appropriate colors.

**Comment by WebFreak001** [comment]
we are using the syntax highlighting file from this repository: https://github.com/textmate/d.tmbundle/blob/master/Syntaxes/D.tmLanguage

It seems like there were some updates to it, I am going to update it soon but if it isnt fixed after that, I'm gonna make an issue and a PR there to add it

**Comment by Vild** [comment]
Small note on your code, it is `Enum.MY_ENUM_VALUE` not just `MY_ENUM_VALUE`.

![img](http://i.imgur.com/LI1ghDk.png)
For me it marks the `MY_ENUM_VALUE`, because it thinks it's a constant (I think). I use Solarized Dark.

I guess the syntax highlighting is partly decided on the theme you use.

**Comment by sprinkle131313** [comment]
Ah yah that's true, I was thinking of an enum with out a name, as is used in the SDL2 derelict library. With the proper way to write it, it still isn't highlighted. At least for the default color scheme.

**Comment by 0xEAB** [comment]
The missing highlighting for class names especially turns into a problem when calling constructors. In such a case almost everything has the same color.

Left: C#
Right: D
Note: I like the idea of highlighting return types in a different color (like it is done at the moment).

![example](https://user-images.githubusercontent.com/15967408/27255587-d870ee36-53a0-11e7-9f91-d020122e154f.png)

**Comment by WebFreak001** [comment]
right now only in the code-d-beta package which will be merged into master eventually, but it's fixed once it's in there. Switched to https://github.com/ysgard/d-struct grammar now because it looks a lot better maintained and the authors suggested me to use it in the atom extension which I will also do
