### ISSUE TITLE
cannot open definition of Symbols defined in dub package

### ISSUE THREAD

**Issue by NikkyAI** [Pure-D/code-d#77]
i encountered this when i tried out the dscord library https://github.com/b1naryth1ef/dscord 
more specifically its example bot implementation

i created a new dub project added the dependency and it works except vs code cannot show me any of the symbols

this happens both in the embedded example bot after cloning dscord (it defines the dependency via relative path `"dscord": {"path": "../"}`) 
and when defining it as normal dependency (in dub.sdl) in a seperate directory

since this works with other packages (and within a file) i think its a bug
(or missing feature?)

vscode developer tools console output:
![](https://aww.moe/ea1cky.png)

**Comment by WebFreak001** [comment]
When you have just started your project in vscode without doing anything and you wait for dub and dcd to initialize (its ready when the `debug`, `application`, `x86_64`, etc in the toolbar at the bottom are there), what does it say in the developer tools?

**Comment by NikkyAI** [comment]
![screenshot 1](https://aww.moe/epthx5.png)
![screenshot 2](https://aww.moe/6rn98u.png)
![screenshot 3](https://aww.moe/ao8hm4.png)

a bit of suff about ldc gcc and windows related stuff.. should not appear on archlinux ?

**Comment by WebFreak001** [comment]
It looks like the package import paths are loaded correctly, so I don't know why goto definition wouldn't work. Just on a sidenote, it seems that the `"d.stdlibPath"` setting isn't setup properly for you. You might wanna change it in the vscode user settings to your paths.

Im assuming you tried both ctrl-clicking on symbols as well as rightclick -> goto definition too

**Comment by NikkyAI** [comment]
yes, the result in the console i linked in the first post
the stdlibrary i can open without problems i think

**Comment by NikkyAI** [comment]
seems to have solved itself by upgrading to dcd-git
thanks for the help
