### ISSUE TITLE
Unable to complete installation with latest LDC

### ISSUE THREAD

**Issue by SrMordred** [Pure-D/code-d#80]
I tried every way without success:

**Automatic Installation:**

`install.bat` 
`all`

output:

```
Using existing git repository for workspace-d
Compiling...
$ dub upgrade
Upgrading project in D:\workspace-d
$ dub build --compiler=ldc2 --combined --build=release
Performing "release" build using ldc2 for x86.
workspace-d 2.7.2+commit.2.g3dc0bef: building configuration "application"...
C:\Users\this_\AppData\Roaming\dub\packages\dub-1.1.0-beta.1\dub\source\dub\internal\sdlang\lexer.d(16): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD
C:\Users\this_\AppData\Roaming\dub\packages\dub-1.1.0-beta.1\dub\source\dub\compilers\utils.d(92): Deprecation: dub.compilers.buildsettings.array is not visible from module utils
Using Visual C++: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
LINK : fatal error LNK1181: cannot open input file 'curl.lib'
Error: `C:\WINDOWS\system32\cmd.exe /s /c "D:\ldc\bin\amd64.bat link.exe"` failed with status: 1181
ldc2 failed with exit code 1181.
Error while compiling workspace-d.
Program exited with code 1
```

**Manual Installation:**
After installing with success all dependencies:

`dub build --build=release --compiler=ldc2`

output:

```
Performing "release" build using ldc2 for x86.
dub 1.1.0-beta.1: building configuration "library"...
C:\Users\this_\AppData\Roaming\dub\packages\dub-1.1.0-beta.1\dub\source\dub\internal\sdlang\lexer.d(16): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD
C:\Users\this_\AppData\Roaming\dub\packages\dub-1.1.0-beta.1\dub\source\dub\compilers\utils.d(92): Deprecation: dub.compilers.buildsettings.array is not visible from module utils
Error: Output file '.dub\obj\utils.obj' for module 'dub.internal.utils' collides with previous module 'dub.compilers.utils'. See the -oq option
ldc2 failed with exit code 1.
```

**Comment by WebFreak001** [comment]
huh, does compiling dub with ldc work?
```
git clone https://github.com/dlang/dub.git
dub build --config=library --build=release --compiler=ldc2
```

**Comment by SrMordred** [comment]
Nop, same error as above:
`Error: Output file '.dub\obj\utils.obj' for module 'dub.internal.utils' collides with previous module 'dub.compilers.utils'. See the -oq option`

**Comment by WebFreak001** [comment]
Then this is an issue with dub, im gonna report it there if it isnt already reported

**Comment by WebFreak001** [comment]
also which ldc version are you using?

**Comment by SrMordred** [comment]
version   d0caa5 (DMD v2.071.2-b2, LLVM 3.9.0git-fbbabf3)

**Comment by WebFreak001** [comment]
See also: https://github.com/dlang/dub/issues/952

**Comment by SrMordred** [comment]
Ok, i tried again with the new LDC version:
DUB version 1.0.0, built on Oct  9 2016
LDC - the LLVM D compiler (1.1.0-beta3)

DCD, DScanner install fine.
dfmt fails: 

`Using existing git repository for workspace-d
Compiling...
$ dub upgrade
Upgrading project in D:\workspace-d
$ dub build --compiler=ldc2 --combined --build=release
Performing "release" build using ldc2 for x86_64.
workspace-d 2.8.0+commit.3.g2367725: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Copying files for dub...
Successfully compiled workspace-d!
Cloning dfmt into C:\Users\this_\AppData\Local\Temp\workspaced-install-636153712996704535
$ git clone -q https://github.com/Hackerpilot/dfmt.git dfmt
Checking out v0.5.0-beta3
$ git checkout -q v0.5.0-beta3
Compiling...
$ dub upgrade
Upgrading project in C:\Users\this_\AppData\Local\Temp\workspaced-install-636153712996704535\dfmt
$ dub build --build=release
Performing "release" build using dmd for x86.
experimental_allocator 2.70.0-b1: building configuration "library"...
..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\package.d(322,13): Error: std.experimental.allocator.common.Ternary at ..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at d:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\package.d(328,13): Error: std.experimental.allocator.common.Ternary at ..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at d:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\package.d(348,13): Error: std.experimental.allocator.common.Ternary at ..\..\..\..\Roaming\dub\packages\experimental_allocator-2.70.0-b1\experimental_allocator\src\std\experimental\allocator\common.d(14,1) conflicts with std.typecons.Ternary at d:\D\dmd2\windows\bin\..\..\src\phobos\std\typecons.d(7427,1)
dmd failed with exit code 1.
Error while compiling dfmt.
Program exited with code 1`

**Comment by WebFreak001** [comment]
Thats a different issue than this one @SrMordred 

If it only fails with dfmt its probably an issue with the dub build script in dfmt. They don't really support dub anyway and only really support building using the makefile/script. Maybe I should use that one instead of dub build

**Comment by WebFreak001** [comment]
This issue is now fixed in the newest dub
