### ISSUE TITLE
Can't open Diet file from errors list

### ISSUE THREAD

**Issue by aka-demik** [Pure-D/code-d#85]
![views](https://cloud.githubusercontent.com/assets/5939623/20097556/14ea586e-a5c0-11e6-9750-f58d32417a46.png)

Real path is `\views\device.dt`, vscode tries to open `\device.dt`

**Comment by WebFreak001** [comment]
Will probably need to scan all string import paths and check for existance of this file. I think I will do that whenever the file extension isn't `.d`

**Comment by WebFreak001** [comment]
ok new version (0.14.2) containing this feature is now released

**Comment by aka-demik** [comment]
Wow. It was super fast.
Thank you.
