### ISSUE TITLE
Select wrong symbol when calling templates without parentheses

### ISSUE THREAD

**Issue by Kozzi11** [Pure-D/code-d#89]
for eg:

    struct S {}
    
    T tem(T)(T t) { 
        return t;
    }
    
    tem!S(S());    // 1
    tem!(S)(S()); // 2

In case 1 if I try to go to symbol S it will select tem declaration instead of S
In case 2 it is OK

**Comment by WebFreak001** [comment]
Reported to DCD: https://github.com/Hackerpilot/DCD/issues/356

If its not too complicated I will probably make a PR there too
