### ISSUE TITLE
Document how to enable completion within dub projects

### ISSUE THREAD

**Issue by dhasenan** [Pure-D/code-d#90]
I opened a folder for a dub project, containing `dub.json` and `src/`. I get completion for anything in phobos or druntime, not for my project or its dub dependencies.

code-d ran dcd as:

```
dcd-server --socketFile /tmp/workspace-d-sockKZD -I/usr/include/dmd/druntime/import -I/usr/include/dmd/phobos
```

workspace-d (started without arguments) does have my project directory as its working directory.

VSCode: Version 1.8.0

workspace-d: 3832ba778b4b9e9271e7239ddec4147f461d9b92

dcd: 83454f10f49da2c95b366206934cf3a88f8ce3f4

**Comment by WebFreak001** [comment]
If the project has been built once before it should give auto completion for dependencies. Note that submodules don't currently work

**Comment by dhasenan** [comment]
Turns out dub didn't like its package cache. I deleted that and rebuilt and everything worked.
