### ISSUE TITLE
v0.15 Install

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/code-d#91]
Tried the new 0.15 version ( with VSC 1.8 ). 

> Install extension: Ok
> Reload
> Install workspace-d: Ok
> Reload
> Could not initialize DCD. See console for details!

... And that is all she wrote. Do not see anything on any of the debug console etc...  No DCD installation or anything happening.

**Comment by WebFreak001** [comment]
windows?

**Comment by Wulfklaue** [comment]
Sorry, forgot to add. Indeed: Windows 10 / PortableApp.

**Comment by WebFreak001** [comment]
workspace-d on windows is currently broken, will fix soon

**Comment by WebFreak001** [comment]
Actually it did work, that issue was my fault. Uh so you don't have DCD and code-d doesn't complain about it being absent?

**Comment by WebFreak001** [comment]
Try using a prebuilt workspace-d and don't forget to compile with LDC and not with DMD
