### ISSUE TITLE
A path in your d.stdlibPath setting doesn't exist. Auto completion might lack some symbols!

### ISSUE THREAD

**Issue by jiafuzhang** [Pure-D/code-d#98]
environment:
  macOS 10.12
  visual studio code 1.8
  dmd 2.072.2
  code-d 0.15.1
warning:
  A path in your d.stdlibPath setting doesn't exist. Auto completion might lack some symbols!
possible:
  "d.stdlibPath": [
    "/usr/include/dmd/druntime/import",
    "/usr/include/dmd/phobos"
  ],
please help!

**Comment by WebFreak001** [comment]
um... Does `/usr/include/dmd/druntime/import` and `/usr/include/dmd/phobos` exist?

If not then change the path to the correct ones. I am not sure what the correct paths are on OSX though. If `/usr/include/dmd2` exists then just replace the dmd in the old folders with dmd2. On windows its `<DInstallPath>\dmd2\src\druntime\import` and `<DInstallPath>\dmd2\phobos`

If you find out where that dmd2 path is just use that + src/druntime/import and phobos. Also can you send what the path was in here, so I can add it in a future release? I had automatic detection of paths depending on platform planned for the future

**Comment by jiafuzhang** [comment]
the path /usr/include/dmd/druntime/import and /usr/include/dmd2 is not exists.
but I finally found a directory like <DInstallPath>:/Library/D/dmd/
the <DInstallPath> directory structure is like this:
- bin
- html
- lib
- man
- samples
- src
- license.txt
- README.TXT
and src directory can be find below src/druntime/import and phobos directory.
I do not know whether it is the <DInstallPath>.
I don't know if it's my computer problem,Please help to judge.

**Comment by WebFreak001** [comment]
Your path should be `["/Library/D/dmd/src/druntime/import", "/Library/D/dmd/src/phobos"]` then
